### ISSUE TITLE
No BE-Module in 6.2

### ISSUE THREAD

**Issue by tgaertner** [dmitryd/typo3-realurl#117]
in realURL v2 the old Entry under Module Info is removed, but the new Backendmodule is only working from Version 7 - son in TYPO3 6.2 there is no way to access the RealURL Management stuff

**Comment by dmitryd** [comment]
Not a bug. Backend modules are available only in TYPO3 7.6 or newer. There are no plans to make them working in 6.2. TYPO3 7.6 and 6.2 are too different.

If you need backend modules in 6.2, you have to stay with realurl 1.x.

**Comment by tgaertner** [comment]
sure, but why not enabling the old menu-entry for 6.2 
actually the compatibility-Version of extension is wrong and should be set to 7.x and bigger

**Comment by dmitryd** [comment]
> why not enabling the old menu-entry for 6.2

It is very badly written. That code is about 10 years old and I do not want to add anything that dirty to the new extension.

> the compatibility-Version of extension is wrong and should be set to 7.x and bigger

No, you still can use realurl 2.x with TYPO3 6.2. In fact, you do not need BE modules. It is not recommended to remove cache entries for realurl 2.x because realurl manages caches automatically.

**Comment by tgaertner** [comment]
ok, thanks for your feedback. (a node of that in the documentation would be nice - or I didn't found it)

**Comment by dmitryd** [comment]
Thanks! Added here: https://github.com/dmitryd/typo3-realurl/wiki/Installing-and-enabling-the-extension#limitations

**Comment by dneuge** [comment]
In case the BE module is actually required for anything I would still consider this a valid bug that should stay open until BE modules are compatible with 6.2. Here's why:

"1.13.6	This is the last maintanance release of realurl 1.x. It is also the last version of realurl that supports TYPO3 4.5. The next version will be realurl 2.0.0 and it will support only TYPO3 6.2 or newer."

=> You said that 1.x will not see any more updates (which includes bugfix releases), so it's not really an option to stay on 1.x for long. You also said that 2.x is supporting TYPO3 6.2 which it isn't as the BE module is missing.

I can understand that you don't have the time to fully support two different TYPO3 releases on your own but since this extension is on GitHub, maybe someone else wants to take a look at making the BE module compatible. So unless it's fixed, I would not close this bug with just "won't fix" as a response. Why not just state _you_ don't plan to support it personally but leave it to others to provide a pull request? :)

6.2 is still supported until next year and maybe even further (via ELTS), so it's a bit early to simply stop support altogether (unless there is actually no reason for a BE module in 6.2 but I don't think that's the case).

**Comment by tgaertner** [comment]
I could live without the BE-Module in my case, but in fact there is currently no fully supported realUrl-Version for TYPO3 6.2 - which is bad because thats one of the most used Extension and like dneuge pointed out already TYPO3 6.2 is still supported and very much in use... so there will be somebody who provides a backport maybe

**Comment by dmitryd** [comment]
Firsts, if you really need BE modules, you can use RealURL 1.x in 6.2 without limitations. It is stable and works.

Secondly, absence of BE moduels for 6.2 is documented. You do not always get everything for older versions of software because it requires too much effort from developers. Except for BE modules, RealURL is compatible with 6.2.

If somebody adds 6.2 support to BE modules, I can test it and integrate if it works. However I have no plans to make it myself. Sorry about that. This project is non-commercial and I really do not want to spent many of my personal hours to code something, which will be unused by majority in half a year time.

Therefore there are three options if you really cannot live without BE modules:
1. Use RealURL 1.13.x
1. Migrate to TYPO3 7.6
1. Code BE modules and share with the rest of the community 😄

**Comment by dmitryd** [comment]
@tgaertner

RealURL 2.x is fully supported for 6.2 except for BE modules.
RealURL 1.x has BE modules and works in 6.2. It is stable and does not require updates.

**Comment by dneuge** [comment]
> If somebody adds 6.2 support to BE modules, I can test it and integrate if it works.

That's exactly my point. :)

I'd just vote for reopening this issue (or some duplicate reported, maybe) so it's visible on the "task list" that is the issue tracker. Even if you won't be the one resolving that issue (just leave it unassigned), it should be visible for others. But if it's closed it may get missed (and also, I would expect duplicates popping up every now and then).

**Comment by dmitryd** [comment]
Generally I keep issues open to show that I will work on them. It is like a task list. Since this is not a task I plan to work on, I prefer it to be closed.

However if somebody wants to work on it, I can re-open. I just don't want to re-open the issue and give people hope without reasons. Hope, this makes sense.

**Comment by tgaertner** [comment]
Thanks for the feedback!! I understand you point of view! And btw thanks for the great work at this Extension in your free time. I can live with the provided solutions.

**Comment by vdoria** [comment]
So what's then the recommended way on clearing the caches without BE module in 6.2?

You said it's not required but https://typo3.org/news/article/cache-flooding-in-typo3-frontend/ actually says we have to...

` If extensions like realurl are used, it is required to flush their caches (and TYPO3 caches as well), so that the new cHash is stored, once the pages are requested.`

**Comment by lisardo2** [comment]
There is a big problem with the realurl cache in version 2. When a backend user names two pages with the same title both pages get the same path in the realurl cache tables. So only one of the two pages is accessable. When the user recognizies the problem he is not able to fix it: he can of course change the page title but not the wrong cache entry. The cache - and of course the false url - remains for 1 month in the database. Every week I get tickets from my users and have to look in the database for wrong cache entries and delete them. Well, or truncate the whole tables.

**Comment by dmitryd** [comment]
@lisardo2 
> There is a big problem with the realurl cache in version 2. When a backend user names two pages with the same title

Go and read the docs.
