### ISSUE TITLE
Crossdomain links can break URL-Cache

### ISSUE THREAD

**Issue by rvock** [dmitryd/typo3-realurl#161]
I have two domains in the same TYPO3 installation.

Page 1 of domain 1 links to itself and to root-page of domain 2. This generates the following Cache-Entries:

page_id | rootpage_id | original_url | speaking_url
----------- | --------------- | --------------- | -----------------
2 | 1 | &L=0&id=2 | en/
1 | 1 | &L=0&id=1 | en/

This will lead to an error when loading domain1/en the next time, because getUrlFromCacheBySpeakingUrl will return the first entry with the incorrect id.

This can be avoided with setting ```config.typolinkCheckRootline = 1``` or ```config. typolinkEnableLinksAcrossDomains = 1``` in TypoScript.

I think, if these settings are false, realurl should avoid creating the cache-entry for pages in the other domain or should trigger a warning.

**Comment by dmitryd** [comment]
That's right. If you link across domains, you have to use `typolinkEnableLinksAcrossDomains = 1`. TSRef clearly [says](https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#typolinkenablelinksacrossdomains):

> This option enables to create links across domains using current domain’s linking scheme.

Without this option you will not be able to link across domains correctly.

Where is the bug here?

**Comment by dmitryd** [comment]
This was always like this, even in RealURL 1.x. Just configure TYPO3 correctly and it will work as expected.

**Comment by rvock** [comment]
I wouldn't say this is a bug, but it creates hard-to-find errors. These errors even still exist, after enabling the TypoScript settings (because the incorrect entries still exist in the cache). It would be nice, if those errors could be prevented with a warning or not writing to the cache.

A little more background: In my current setup, the pages were independent of each other and even used different ```config.sys_language_uid``` settings for the different domains. If this is the case, typolinkEnableLinksAcrossDomains should not be enabled, because the links will use the incorrect language-prefix. The error occured, after an editor copied a content-element from one page to another and didn't adjust the link to the root-page.

**Comment by dmitryd** [comment]
Well, RealURL can do a lot but not everything. It is intended for more or less typical setup.

If you link across domains, you have to use that option for correct linking. No other way. It is not just for RealURL but also [core uses it](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L5931).

Your best chance otherwise is an external URL (as it was before TYPO3 4.5 when linking across domains was implemented).

It is hard to expect that the system will be error free if it is not configured according to expectations. Would you put gasoline into the diesel car and expect it to drive without errors or tell the maker that you have a problem that diesel car does not run gasoline? Same is here. There is a certain set of expectations and requirements that you have to follow if you use RealURL. While TYPO3 allows you to do anything, not everything is guaranteed to work with it.

There is also a tradeoff between complexity, stability and support for everything. The more unusual configurations are supported, the more would be complexity and the less will be stability. My aim is to support typical configurations as much as possible. All others will require custom solutions. Unusual? No.  Quite typical in our world.

I understand that it may cause problems. Therefore I plan to add more information to the documentation for such cases.

**Comment by rvock** [comment]
I know, that core also does not work, if the setting is not set. But the difference to core is, that only the incorrect link will not work. With realurl the root-page will generate a 404 the next time, someone tries to access it. That's why I thought a "convenience warning" would be a good idea to prevent other people from searching for strange errors.

But of course I am ok, with whatever you decide :) I already adjusted our base-configuration to prevent this error in all future installations.

**Comment by dmitryd** [comment]
I am not sure what kind of warning you expect :) RealURL just decodes or encodes URLs, it has no UI. If the system is not configured correctly, than RealURL cannot produce correct URLs. It is the same as your car: if you put wrong fuel into it, it cannot run.

This is *not* a bug. Everybody has to do its homework properly. RealURL will not try to recover for badly configured systems because it expects others to configure the system according to requirements.
