### ISSUE TITLE
Exception in Frontend: #1343589451: Could not fetch page data for uid X

### ISSUE THREAD

**Issue by einpraegsam** [dmitryd/typo3-realurl#200]
Maybe related to https://github.com/dmitryd/typo3-realurl/issues/45

We migrated a system from realurl 1.x to 2.0.14.
On a page there is a text element with a RTE with some typolinks:
`<link 10781 _blank internal-link>Institut für Finanzmathematik</link>`

The problem is, that the parent page to uid 10781 (with uid 10667) is deleted=1 while 10781 is not deleted. Nevertheless the frontend breaks with an exception.
With realurl 1.13.6 there was no problem with rendering the page.

**Comment by dmitryd** [comment]
RealURL 2 is not 100% backwards compatible with version 1. It tries to use as much TYPO3 API instead of direct database access as possible. For TYPO3 is a broken rootline to have such link. It is better that you move the page. I do not think this should be "fixed" in realurl. The page is inaccessible anyway. It means data integrity on the site is broken and the exception has valid reasons.

**Comment by dmitryd** [comment]
@janslu Sorry, I do not do anything beyond realurl bug fixing and some feature requests. Please, ask for support in TYPO3 mailing lists or in Slack chat.

**Comment by patkar** [comment]
There should be a check if the page is still accessible in the whole rootline and not only the page. This sounds like a serious bug. IMHO checking only the page and not the whole rootline is not using the TYPO3 API enough ;)

And the use case is given in many big installations where editors use a _trash_ folder instead of deleting sites

**Comment by dmitryd** [comment]
That's not RealURL's job. RealURL only decodes and encodes URLs. Nothing else. If page is not accessible you properly get a 404.

**Comment by janslu** [comment]
Dmitry, sorry for taking your time. I know you are usually pretty attached to the way things already are, and it doesn't change my usual admiration for the quality of your work. I don't expect a fix or a reply even, I get it. 

But if, as you say, it's job is just to decode/encode urls, why does it throw an exception when the linked page is outside of the tree? Shouldn't it just skip the rewrite and just "let it be"? I don't get the necessity of throwing an exception on a site set up for production because of a link going outside the tree. I'd much rather have broken links on my site than several unavailable pages only because they link to a page that is no longer available...

**Comment by dmitryd** [comment]
Yes, this can be a good feature. But I will need a configuration setting for that to preserve the default behavior. Let me think.

**Comment by dmitryd** [comment]
> There should be a check if the page is still accessible in the whole rootline and not only the page. This sounds like a serious bug. IMHO checking only the page and not the whole rootline is not using the TYPO3 API enough

The exception is not thrown by RealURL. It is thrown by the TYPO3 core when it cannot get the rootline for the page. RealURL uses rootline to create a page path.

What you ask me to do, is to ignore an error about non-accessible page and silently return un-encoded path. Next I'll be getting bug reports about non-encoded URLs... So I am not happy about changing this. It is site mainatiner's job to ensure integrity of the site. There is link checker or you can ask editors to watch what they are doing... Of course, it is easier to ask somebody else to just mask errors. But it does not see right to me. If I get an exception on the site, than there is something wrong and it should be fixed, not silently ignored.

Possible patch is below but I think it is a wrong way to go.

```diff
diff --git a/Classes/Encoder/UrlEncoder.php b/Classes/Encoder/UrlEncoder.php
index eef9361..a314661 100644
--- a/Classes/Encoder/UrlEncoder.php
+++ b/Classes/Encoder/UrlEncoder.php
@@ -31,6 +31,7 @@ namespace DmitryDulepov\Realurl\Encoder;
 
 use DmitryDulepov\Realurl\Configuration\ConfigurationReader;
 use DmitryDulepov\Realurl\EncodeDecoderBase;
+use TYPO3\CMS\Backend\Form\Exception;
 use TYPO3\CMS\Core\Utility\GeneralUtility;
 use TYPO3\CMS\Core\Utility\MathUtility;
 use TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer;
@@ -785,6 +786,7 @@ class UrlEncoder extends EncodeDecoderBase {
 	 * Encodes the URL.
 	 *
 	 * @return void
+	 * @throws \Exception
 	 */
 	protected function executeEncoder() {
 		$this->parseUrlParameters();
@@ -796,7 +798,18 @@ class UrlEncoder extends EncodeDecoderBase {
 		$this->initializeUrlPrepend();
 		if (!$this->fetchFromtUrlCache()) {
 			$this->encodePreVars();
-			$this->encodePathComponents();
+			try {
+				$this->encodePathComponents();
+			}
+			catch (\Exception $e) {
+				if ($e->getCode() === 1343589451) {
+					// Rootline failure: "Could not fetch page data for uid X"
+					// Reset and quit. See https://github.com/dmitryd/typo3-realurl/issues/200
+					$this->encodedUrl = $this->urlToEncode;
+					return;
+				}
+				throw $e;
+			}
 			$this->encodeFixedPostVars();
 			$this->encodePostVarSets();
 			$this->handleFileName();
```

**Comment by janslu** [comment]
Thank you. I absolutely understand your position and am grateful for the explanation. I will consider my options but the patch from you seems like a great stopgap resolve until we, as a team, work out a better workflow.

**Comment by dmitryd** [comment]
Integrated that fix.
