### ISSUE TITLE
Incorrect Paths in URL. sys_language_uid not considered

### ISSUE THREAD

**Issue by hojaonline** [dmitryd/typo3-realurl#214]
[UrlEncoder.php.patch.zip](https://github.com/dmitryd/typo3-realurl/files/389994/UrlEncoder.php.patch.zip)
Dear Dmitry,
There is a serious issue in the encode url section. I dont know why you're not considering whether the sys_language_uid is set or not in that condition. In that section only **'L'** Parameter in querystring is considered for setting the language id. In my website there will be no **'L'** parameter passed in the polish language and there are 3 languages were set in the backend like **Default | Polish**. Where Default is english in backend and in fact in frontend the default language is Polish and secondary language is English. ( Set by **config.sys_language_uid**). So according to the current encoding logic it encodes the url in the function **createPathComponentUsingRootline** using the 'L' value in English. Which is completely wrong. So I patched your code and put a single condition to check whether the sys_language_uid is set and 'L' value is not set.

Like this
```
/**
		 * Patch for fixing the incorrect default language set occurance - Date : 28-07-2016
		 */
[UrlEncoder.php.patch.zip](https://github.com/dmitryd/typo3-realurl/files/389991/UrlEncoder.php.patch.zip)


		$this->originalUrlParameters['L'] = ( isset($GLOBALS['TSFE']->sys_language_uid) && $GLOBALS['TSFE']->sys_language_uid > 0 && !isset($this->originalUrlParameters['L']) )?  $GLOBALS['TSFE']->sys_language_uid : $this->originalUrlParameters['L'];
```

**Comment by dmitryd** [comment]
Please, read the docs for integrators about configuring your system properly. Please, ask for support in mailing lists, not here.

**Comment by AnuBN** [comment]
Hi Dmitry,
By the way, if you are mentioning about `config.defaultGetVars.L`, In my instance I am handling around 50 domains with different default langauges. You are saying that I want to configure the above script in every domain manually ??

Then kudos for the above patch. We can't rely on L parameter always, can we ??

**Comment by hojaonline** [comment]
@dmitryd : I dont know what's wrong with the existing configuration which creates this issue. I have a huge cms system with 60 + websites and more than 35 languages in a single TYPO3 installation. So the basic configuration which I added related to realurl is 
```
config {
  sys_language_uid = 17
  language = pl
}
```
Where Default in Backend (Pages Table ) & Poland From (page_overlay table)
If I set  
config.defaultGetVars .L = 17 like @AnuBN  mentioned above.

Then for removing the language code from url I need to add the proper settings in realurl conf or htaccess right?. It takes a lot of time for big TYPO3 Installations...... 
Kindly revert.

**Comment by dmitryd** [comment]
> Kindly revert.

Kindly no. If you use realurl, you have to follow rules, not realurl has to follow yours.

Switch to cooluri if you wish.

**Comment by hojaonline** [comment]
sorry for the inconvenience. May I know if there any specific logical reasons for ignoring the sys_language_uid in your extension ?

**Comment by dmitryd** [comment]
The reason is because RealURL must not take `sys_language_uid` into account. RealURL receives a URL from the TYPO3 core and RealURL does not know why core asked to encode this particular URL. It must convert the url "as is". For example, URL for the default language provided by the core can look like `/index.php?id=1&L=0` or `/index.php?id=1`. For a second language it can be `index.php?id=1&L=15`. RealURL accepts this and encodes what it receives.

Regarding your case, I still believe it is a configuration issue and you should read Notes for integrators in the wiki of this project. You can have different default languages in FE and BE. However you have to add certain TS options for this to work. But it is not a bug, so there is no reason to have it here. I do not offer support beyond bugs and feature requests. You should ask in mailing lists or in Slack groups if you cannot solve it yourself.

I hope documentation helps to solve this.
