### ISSUE TITLE
Typo3 7.6.10, Real url 2.0.14, Tx_news 4.3.0 - Page not found if BE User log in

### ISSUE THREAD

**Issue by droomdre** [dmitryd/typo3-realurl#224]
Hello,
with the last Version of realurl 1.13.6 i had no issue when opening the news detail view and being log to the Back-end.
With the version 2.0.14, i always get a pagenotfound error 404 if i open a news detail view and i'm log in to the backend on the same browser.

My news Detailview Configuration:
```
'newsDetailConfiguration' => array(  //tx_news   	
                        array(
                                'GETvar' => 'tx_news_pi1[news]',
                                'lookUpTable' => array(
                                        'table' => 'tx_news_domain_model_news',
                                        'id_field' => 'uid',   
                                	'alias_field' => "IF(alternative_title!='', alternative_title, title)",
                                        'addWhereClause' => ' AND NOT deleted',
                                        'useUniqueCache' => 1,
                                        'useUniqueCache_conf' => array(
                                                'strtolower' => 1,
                                                'spaceCharacter' => '-'
                                        ),
                                        'languageGetVar' => 'L',
                                        'languageExceptionUids' => '',
                                        'languageField' => 'sys_language_uid',
                                        'transOrigPointerField' => 'l10n_parent',
                                        'autoUpdate' => 1,
                                        'expireDays' => 180,
                                )
                        ),
),
```
.htaccess has not been changed.

**Comment by MichaelSchreiner** [comment]
The configuration works for me with 2.0.15.
Like mentioned in another [thread](https://github.com/dmitryd/typo3-realurl/issues/62#issuecomment-193765273), you should use <> instead of != for comparison.
However, I have experienced a problem with the tx_news detail view when logged into the backend which can result in giving you a 404 error page. There seems to be a cache for the detail view which is only used, when you are logged into the backend. The view then ignores the uid given in the URL and always displays the news which was selected first. When you force a reload of the page, the correct news is displayed, cached and from then on always displayed in the detail view. In a browser session without BE login everything works fine. So if you had called the detail view with a non existing news id initialy, you end up with a 404 page when logged in, and a working news page without login.

**Comment by dmitryd** [comment]
I have an idea how to fix it.

**Comment by AndreasA** [comment]
I think this is actually related to this:
https://github.com/dmitryd/typo3-realurl/issues/237

**Comment by dmitryd** [comment]
This will work ok in 2.1.0 because URL data will be used there in the Backend as well.
