### ISSUE TITLE
Wrong 404 with existing records

### ISSUE THREAD

**Issue by webian** [dmitryd/typo3-realurl#238]
Hello @dmitryd, in development branch of Realurl 2 probably there's a problem with array_shift of $pathSegments in method `decodePostVarSets`. I get 404 with [this auto configuration of EXT:cal](http://pastebin.com/jeKWvSyq).

Long story short: the while condition `count($pathSegments)` should be `count($pathSegments) > 0 && $pathSegments[0] <> ''` because the method `decodeSingleVariable` could change $pathSegments to have only one element = ''.  So the `while` continue and ends up in method `handleNonExistingPostVarSet` and so the 404.

I can make a PR if needed but I'm not sure if changing the condition is the right solution.

Best regards,
Christian

**Comment by dmitryd** [comment]
`count($pathSegments)` is the same as `count($pathSegments) > 0` but `$pathSegments[0] <> ''` is probably wrong because path segments can be empty in certain cases.

I will look deeper into it. Can you post some urls that do not work here and also a better description of  a problem (just "there is a problem" does not tell me much).
