### ISSUE TITLE
Update to v. 2.0.15 tt_news catmenu and pagebrowser not working any more

### ISSUE THREAD

**Issue by triograf** [dmitryd/typo3-realurl#244]
After updating realurl to v. 2.0.15. (TYPO3 v. 7.6.9) the category menu and the pagebrowser of the ext tt_news are not working anymore. The url changes but the content in the frontend remains the same without any change.

reaulurl for tt_news is configured like this:

```
'postVarSets' => array(
				'_DEFAULT' => array(

					'artikel' => array(
						array(
							'GETvar' => 'tx_ttnews[tt_news]',
							'lookUpTable' => array(
								'table' => 'tt_news',
								'id_field' => 'uid',
								'alias_field' => 'title',
								'addWhereClause' => ' AND NOT deleted',
								'useUniqueCache' => 1,
								'useUniqueCache_conf' => array(
									'strtolower' => 1,
									'spaceCharacter' => '-',
								),
							),
						),
					),

					'kategorie' => array(
						array(
							'GETvar' => 'tx_ttnews[cat]',
							'lookUpTable' => array(
								'table' => 'tt_news_cat',
								'id_field' => 'uid',
								'alias_field' => 'title',
								'addWhereClause' => ' AND NOT deleted',
								'useUniqueCache' => 1,
								'useUniqueCache_conf' => array(
									'strtolower' => 1,
									'spaceCharacter' => '-',
								),
							),
						),
					),

					'browse' => array(
						array(
							'GETvar' => 'tx_ttnews[pointer]',
						),
					),
				),
			),
```

**Comment by fiedomedia** [comment]
Same issue with ext:news: news URL of single view changes, but shows always the same news.
Deactivating TYPO3-Cache helps, but is no solution.

**Comment by dmitryd** [comment]
Guys, please, ask in mailing lists. You have cHash issues in links. This is not something that realurl can fix for you anymore. It did until security team decided it is not wanted. So you have to set cHash correctly now...

**Comment by AndreasA** [comment]
What happens with the 2.0.15 change if one calls an URL that requires a cHash prior to the Link being generated?
If I understand it correctly that means that no cache entry was stored and therefore in the decoder there is no cHash value at all which means that decoding will fails and will result in 404 if pageNotFoundOnCHashError is enabled?

Also during realurl encoding it is possible that parameters are removed from URL due to nomatch bypass and that would change the cHash from the original calculated URL although as long as the speaking URL and the desired URL are stored that shouldn't be a problem. 

I think one solution would be to only generate cHash if all parameters are valid speaking URL parameters.
No arbitrary parameters that could have been modififed in any way possible as all would have been decoded (or removed) by realurl decoding process.

All other URLs would have the cHash appended GET parameter anyway.

**Comment by dmitryd** [comment]
@AndreasA You are repeating approximately the same arguments that I told to the security team. Guess the answer.

**Comment by seirerman** [comment]
Since updating from 2.0.14 to 2.0.15 I get broken links for tt_news detail views, too.
The RealURL config and therefore the URLs stayed the same.

Even with the RealURL autoconfig the errors remain. No hints in the Apache error log, either.

I also noticed that after truncating the RealURL tables the URLs work once, but fail to load on the second try (cache is disabled on the test site).

**Comment by dmitryd** [comment]
@seirerman You should never have cache disabled, even on a test site. Disabling it on a test site and enable in production, makes your two environments very different. This way your test site does not represent your live site.

And with 2.0.15 you will always get 404s if you have cache disabled. This may change in 2.1.0 because I am thinking about bringing this functionality back but as optional (it will require special enabling in the configuration).

**Comment by AndreasA** [comment]
@dmitryd 
So only calculating the cHash if all arguments were decoded via realurl is a no go too?

**Comment by seirerman** [comment]
Well, i humbly disagree with you on the no_cache thing for developmental sites.

But even with config.no_cache=0 I still get the same behaviour (404s on the second try).

**Comment by dmitryd** [comment]
@AndreasA This is what realurl actually did before 2.0.15: if there is no entry in the url cache and there are decoded URL parameters, it created a cHash. This allowed `pageNotFoundOnCHashError` check and `reqCHash()` functions to see a proper cHash for the URL. In my opinion it is a valid part of the decoding process because the encoder strips cHash. So if the encoder strips it, the decoder should re-create it. However, it opens possibilities for the attacker to request every page of the site with, for example, URL part of the tx_news and potentially fill thousands of page cache entries. Thus it can be treated as DoS attack because page cache may grow too much.

In my opinion this should not be realurl issue but a page cache issue. Cache should be able to keep its size under control and make sure that it works efficiently even with many entries. For example, memcached does that: it has a limit to the memory and starts discarding less used entries when there are too many of them. Nothing like that exists in TYPO3 caching framework. It just adds and adds new data. However security team disagreed that it should be solved on the page cache side. I do not blame them and understand their position: it is easier to remove cHash recalculation that to rework caching framework to keep caches under control. So we got easy but worse solution to the page cache DoS issue. If I were on their side, I would probably vote for such solution as well. Given lack of full time TYPO3 core developers, solving this on the core side is very unlikely.

**Comment by dmitryd** [comment]
@seirerman 

> Well, i humbly disagree with you on the no_cache thing for developmental sites.

It is up to you :) But you should always realize that you put your def site into completely different behavior than your live site. For example, if you forget a `typolink.userCacheHash = 1`, it will work properly on your dev but it will not work on your live host. Just beware of consequences.

**Comment by seirerman** [comment]
@dmitryd: True, but my point still stands: I get 404s regardless of the cache settings with RealURL 2.0.15 

And you mean useCacheHash, right?

**Comment by dmitryd** [comment]
@seirerman 

> True, but my point still stands: I get 404s regardless of the cache settings with RealURL 2.0.15

Yes, you will get those if you are logged in to BE because that disables realurl cache.

> And you mean useCacheHash, right?

Yes. That was a typo.

**Comment by seirerman** [comment]
@dmitryd: But I am not logged in!

**Comment by dmitryd** [comment]
@seirerman Not logged in OR have cache disabled is the same. See how it works with and without cache.

**With cache**
User opens the page. All links are processed by the encoder and saved to the url cache with cHash. When the user clicks on the link, the decoder checks the cache, finds the "speaking" url and a corresponding original url with cHash. It re-creates all parameters including cHash in `$_GET`. TYPO3 is happy.

**When BE user is logged in or URL cache is disabled**
User opens the page. All links are processed by the encoder but not saved to the url cache. When the user clicks on the link, the decoder checks the cache, finds nothing and decodes the URL according to the configuration.

Prior to version 2.0.15 the decoder also checked if there are URL parameters but cHash is missing. If yes and yes, it would create a cHash. Since 2.0.15 cHash is not created. Than the decoder puts all parameters to `$_GET`. TYPO3 calls the plugin. The plugin tells TYPO3 that cHash is required (`$GLOBALS['TSFE']->reqCHash()`). TYPO3 checks if cHash exists, finds none and aborts with a 404. There is your current 404.

**Comment by dmitryd** [comment]
Until 2.1.0 is out, everybody, who suffer from this issue, can use one of two solutions:

- Make sure that URL cache is enabled (no `cache => disable = true` in your config). Use a different browser to see FE when you are logged in to BE.
- Install 2.0.14 again (if you cannot get it from TER, use `dmitryd\typo3-realurl` in composer instead of `typo3-ter/realurl`)

**Comment by seirerman** [comment]
The pages are cached (config.no_cache=0) AND I'm not logged in (Different URL than BE, different browser, doesn't matter), is what I'm trying to say. ;-)

Anyway, would going back to RealURL 1.13.6 be a valid option, too, regarding the DOS possibility and until 2.1.0 comes out?
We're still on TYPO3 6.2 and I never had a problem with that version.

**Comment by triograf** [comment]
@dmitryd thanks for the suggested two solutions until v. 2.1.0 is out.

But will v. 2.1.0  fix the initial problem i had with the catmenu and the page browser of tt_news? Or is that just a configurations issue which should be fixed in the realurlconfiguration.php itself regardless of the realurl version?

Thank you for the quick support/response.

**Comment by dmitryd** [comment]
@triograf The issue should not happen if you do not clear or disable URL cache.

**Comment by dmitryd** [comment]
Relevant: [calculateChashIfMissing](https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#calculatechashifmissing)

**Comment by AndreasA** [comment]
Shouldn't that ifMissing actually solve the DoS attack too? Because there can only be one cHash value stored then.

In regards to DoS: That is why I said we would have to add a check that only does cHash calculation if ALL parameters are coming from realurl and are of a limited ranch, like lookupTable, valueMap.
And maybe userFunc if it sets a certain value.
Shouldn't that ifMissing actually solve the DoS attack too? Because there can only be one cHash value stored then.

In regards to DoS: That is why I said we would have to add a check that only does cHash calculation if ALL parameters are coming from realurl and are of a limited ranch, like lookupTable, valueMap.
And maybe userFunc if it sets a certain value.


Another thing: So one should never clear the decode cache afterwards? 
What about old URLs that have to be updated? 
I don't want to clear the cache here per page, would it be enough to clear the encode cache or maybe storing cHash values separate again would be a good idea?

**Comment by dmitryd** [comment]
> That is why I said we would have to add a check that only does cHash calculation if ALL parameters are coming from realurl and are of a limited ranch, like lookupTable, valueMap. And maybe userFunc if it sets a certain value.

Not really because `noMatch=bypass` can remove some variables that were in the original URL and thus change cHash.

> You are probably right though that the best solution would be better page cache handling in the core in regards to the DoS attack but I also don't think it is likely to happen in the near future.

Unfortunately, yes.

> Another thing: So one should never clear the decode cache afterwards? What about old URLs that have to be updated? 

Starting from 2.1.0, realurl will handle page renames by adding expiration time to such URLs. So URL cache clearing will be semi-automatic.

I'd say that cache should be left alone. Realurl is good enough to manage it.

**Comment by triograf** [comment]
@dmitryd but i did not touched nor disabled the url cache. Just updated to v. 2.0.15. After that the catmenu and the page browser did not work. The detail page work as expected.
So where’s the fault? Wrong config?

**Comment by dmitryd** [comment]
@triograf Check if you actually have entries in the URL log on the corresponding page.

**Comment by AndreasA** [comment]
> Starting from 2.1.0, realurl will handle page renames by adding expiration time to such URLs. So URL cache clearing will be semi-automatic.

That's good because I already had that problem once (old URLs).

In that regard: Will a change of a pagename (in any language) clear all URLs of that page, also that of different languages?
Because due to content fallback that might need to be cleared too - at least if you have a corresponding getPageOverlay Hook.

**Comment by dmitryd** [comment]
It will mark URL as expired. If somebody visits such URL, he will be redirected to the current URL. And only the URL for the edited language is marked as expired.

**Comment by AndreasA** [comment]
So if one wants to support content fallback or similar additional hooks will be required?

Would be great if you add a hook there for things like that.

The redirect will be 301 or can it be defined what type of redirect?

**Comment by helhum** [comment]
> What happens with the 2.0.15 change if one calls an URL that requires a cHash prior to the Link being generated?

@AndreasA @dmitryd 

Let's see how TYPO3 works without realurl:

Can anybody know the URI to a location (e.g. news detail view) which requires a cHash *before* TYPO3 generated it?  No. It is impossible because the cHash is built using (some) URI arguments **and** a secret (encryption key), which is only known to TYPO3. This means that a URI (which requires a cHash to work correctly) does **not exist** before TYPO3 created it!
The secret is included in the cHash to not allow attackers to create arbitrary cache entries.

This is a base concept of TYPO3 (page caching), which we have to live with until we change it.

realurl as an extension to TYPO3 has to build upon these concepts.

As a logical consequence, "if one calls an URL that requires a cHash prior to the Link being generated" it'll fail like any other link that requires a cHash even without realurl.

If realurl now removes the cHash from the URL, it is responsible to remember the original URL including the removed including the cHash argument. Since this is vital information it should **NOT** be stored in a volatile cache, but in a more persistent place to make clear that removing this information equals removing the URLs resulting in a 404.

**Comment by dmitryd** [comment]
> Can anybody know the URI to a location (e.g. news detail view) which requires a cHash before TYPO3 generated it? No.

Actually it can be guessed easily. Sometimes I even type those urls manually during development :)

> As a logical consequence, "if one calls an URL that requires a cHash prior to the Link being generated" it'll fail like any other link that requires a cHash even without realurl.

Incorrect :( This will work only if cHash is persistently stored somewhere for the URL.

> If realurl now removes the cHash from the URL, it is responsible to remember the original URL including the removed including the cHash argument....

All correct but I want to add/stress two points here:
1. Realurl always removed cHash (even in 1.x) if there are no more parameters in the URL
1. Realurl stores cHash **if** URL cache is enabled. In version 1.x there was a separate cHash cache but often it got out of control and people struggled with millions of entries in that cache, which may cause DoS with realurl 1.x. Version 2.x solves the issue by storing cHash together with URL in the URL cache. If URL cache is not filled in or cleared or disabled, the only way to get a proper cHash is to re-calculate it. Therefore it is very important to leave realurl caches alone and not touch them.

**Comment by AndreasA** [comment]
> Can anybody know the URI to a location (e.g. news detail view) which requires a cHash before TYPO3 generated it? No. It is impossible because the cHash is built using (some) URI arguments and a secret (encryption key), which is only known to TYPO3. This means that a URI (which requires a cHash to work correctly) does not exist before TYPO3 created it!

That is TRUE for URLs that contain a cHash but it might not be true for URLs from realurl.

Example:
1.) Detail page of news http://example.org/news/detail/myarticle/
2.) Google indexes the detail page above or the link has been shared via facebook
3.) My realurl cache has gotten rather big
OR I have some URLs in it with old encoding, so I decide to clear them.

Now I have the following scenario:
Realrul has lost the cHash value and the URL itself never contained the cHash value.

So if I access the news detail page via Google before it is accessed otherwise, I will run into problems.
The only solution would be to upon clearing the realurl Cache to also regenerate all possible URLs.

**Comment by helhum** [comment]
> Actually it can be guessed easily.

Oh, really? Can you please guess the cHash for this URL for me please? `index.php?id=4&tx_news_pi1%5Bnews%5D=1&L=100`

> This will work only if cHash is persistently stored somewhere for the URL

That is precisely my point! And this storage must **not** be a volatile cache.

**Comment by dmitryd** [comment]
I mean that URL can be guessed easily :)

Current storage for URL (and cHash) is database. It is not volatile. But in certain cases it can be empty. As mentioned before: URL cache can be cleared but people still can come, for example, from Google. Thus there is no place where to get cHash from. It can only be calculated during decoding.

**Comment by helhum** [comment]
> URL cache can be cleared

pages table can be cleared as well. My point is to not name it "cache". A cache is volatile by definition. If it is not there, it can be regenerated. This is not true currently for the cHash information.

**Comment by dmitryd** [comment]
Well, those caches were not required before 2.0.15 :) The only required table was unique alias table and that is not cache. Cache tables could be cleared any time and realurl was able to re-create all data perfectly.

With 2.0.15 URL cache, in fact, became mandatory. I still believe this was not a right move to disable cHash calculation. The problem with a possible cache overflow should be solved in the caching framework, not in the realurl. cHash calculation is a part of URL decoding process. The part, which can be abused is caching framework, so it should prevent the abuse. And if you think further, nothing prevents a programmer from filling any cache table with millions of records and exhausting system resources. Caching framework just don't have any protection against abuse. Again, see how memcached does it: you can never abuse memcached, it will just start dropping old data if it does not fit into limits.

**Comment by helhum** [comment]
With the goal to remove the cHash from the URL, the minimum information that would need to be stored persistently is the result of `\TYPO3\CMS\Frontend\Page\CacheHashCalculator::getRelevantParameters` (hash of serialized array with encryption key removed of course). And it must be stored once the URL is generated.
No information can be removed that store, otherwise it'll break cHash URLs if not regenerated.

On decoding realurl can then reconstruct the query string, call `\TYPO3\CMS\Frontend\Page\CacheHashCalculator::getRelevantParameters` and if it finds a match in the persistent store, generate the cHash for this query string.

The storage overhead would be roughly 32 bytes (let it be 256 bytes for additional meta information) per page cache entry (which is the one and only purpose of a cHash).

I don't see any flaw in this. It is secure, adapts to TYPO3 behavior, cannot break and has little storage overhead.

Am I wrong?

**Comment by dmitryd** [comment]
Yup. You are talking about having an equivalent to `tx_realurl_chashcache` in v 1.x. That proved to be bad idea because there is no hard connection to actual URLs and that table gets out of control very quickly. I've seen about 10 million records in that table on one swiss web site and it slowed the whole system down a lot. It was quite common problem for v 1.x. I regularly got questions like "How can I prevent this table from growing so big?". There is no answer. And that table had just URL hash and cHash, so each record was very small but amount of data took gigabytes. Some people even set up cron jobs to empty this table weekly!

v2 stores cHash together with URL, where cHash belongs. But if the URL is removed, so is cHash. Very small, very efficient.

Why cannot it be the same done for v1 way? Because some people remove URLs manually. Some have all kind of "management" or "realurl cache" extensions that do their own magic about realurl tables (but users blame realurl for all kind of errors after that magic). And so on. So it proved to be a bad idea to make anything more complex than one table per one unit of data. So there are three units now: path, url and alias. Each lives in a separate table.

I thought about design of v2 for more than half a year. I believe that existing structure is much better than one we had in v1.

**Comment by helhum** [comment]
> Well, those caches were not required before 2.0.15

Sure. And that is why an attacker could create an infinite amount of cache entries by just adding arbitrary arguments to an URL for which realurl in these versions calculated a cHash.

And even if TYPO3 had perfect garbage collection for caches (you could easily switch pages cache to memcache), an attacker could still fill up the cache with useless entries and slow down (or take down) a page easily.

As long as realurl is in TER, the security team has the responsibility to tell users about issues with potential security impact. Beyond this point everybody has the option to care or not.

If you and other realurl users are happy with a vulnerability in place, nobody will hinder you going this path.

I try to give advice. It is up to you to follow or ignore it.

**Comment by dmitryd** [comment]
From realurl point of view the whole thing should be different. Realurl should be able to tell TYPO3 something like: "For this particular request do not check cHash at the start. But ***if and only if*** a plugin on this page requires cHash, store the content to the page cache as if there is a proper cHash for the current set of parameters". This way the problem will be solved once and forever. There will be no need to calculate cHash in realurl, no way for anybody to fill up the cache with useless entries. Quite easy to implement in the core, by the way.

However until core provides such service, realurl just has to take care of cHash itself. Realurl's job is to encode and decode URLs. If the URL looks like it should have cHash, realurl has to create it or users have to see 404s. I prefer to show pages to the user instead of showing 404s. Nobody will want a CMS that shows 404s due to some strange internal reasons. Everybody want their web site delivered. This is what realurl tries to guarantee with its current design. In fact, its current design is an attempt to work around multiple limitations of the core.

Realurl is not an easy thing. It was, it is, and it will always be a hack on top of TYPO3. Since it is a hack, it has to use dirty methods until there are better ways to do it.

**Comment by helhum** [comment]
> You are talking about having an equivalent to tx_realurl_chashcache in v 1.x

uhm, no.

Let's look at the code:

https://github.com/dmitryd/typo3-realurl/blob/realurl_1x/class.tx_realurl.php#L834-L838

A hash over the newly generated URL is stored along with the cHash value. That is absolutely **not** what I suggest, because it would mean having multiple entries for one cHash, which indeed does not make sense.

I suggested to **NOT** store the cHash at all, but the `$cHashParameters`. That is not what happend in realurl 1.x: https://github.com/dmitryd/typo3-realurl/blob/realurl_1x/class.tx_realurl.php#L829

**Comment by dmitryd** [comment]
You forget about noMatch=bypass. It may remove some URL parameters. Thus the list of parameters stored in your offered table will be different from the list that realurl decodes and realurl will not be able to find cHash. This is one of reasons why v1 stores cHash for the speaking URL, not for URL parameters.

**Comment by helhum** [comment]
> Everybody want their web site delivered. 

I agree

> This is what realurl tries to guarantee with its current design

Except when it enables cases where the website will not delivered at all any more

> In fact, its current design is an attempt to work around multiple limitations of the core

I agree on the limitations of the core and only add that the workaround introduced by realurl introduces a vulnerability.

We are back to the beginning of our conversation sadly. Do whatever you please, but you can never convince me to use functionality, which introduces vulnerabilities.

**Comment by dmitryd** [comment]
> you can never convince me to use functionality, which introduces vulnerabilities.

I have no intention to do that :) People are born free and they are free to have different believes and opinions. I respect that. But you can also see people here in this thread, who think that it is not a vulnerability but a valid and useful feature. I think so too. When this feature was created, I expected that sooner or later somebody will raise this question. But I thought reasons behind this feature would be important enough to trigger a better handling of caches inside the core.

If I were in the core team, I would probably propose code changes myself. But since I stopped posting code there for a reason, I can only hope that somebody else will implement it sooner or later.

In fact, I was very close to the change to get rid of cHash in the core completely. It was quite interesting idea because it could simplify many things for devs and integrators and even solve cHash+USER_INT issues. But that was a side track from realurl, so I did not continue with that.

**Comment by AndreasA** [comment]
I think the idea about storing the cHash relevant parameters minus the bypass values in a table that is not called cache would be a valid first solution.
Especially as users would never delete that table as it is not called cache.

Another thing is that it doesn't care about pageid or speaking url names, so it shouldn't grow that much either

**Comment by dmitryd** [comment]
Suppose a news article is deleted. Who will clean that table from those entries? It is not that easy to find necessary entries.

**Comment by AndreasA** [comment]
Or to be more precise a hash of those values
Which means realurl would only need to check if the decode parameters hash is anywhere in that table.
Can be quite fast too by making that hash a key

**Comment by AndreasA** [comment]
Currently that value needs to be forever in the decode / encode caches which is even worse

**Comment by AndreasA** [comment]
You could also add those entries to the refindex which would allow you to detect if the reference is deleted but ecen without it would be better than only having the chash in thrme cache tables which contains the whole url information.

**Comment by AndreasA** [comment]
Sorry for multiple posts but github mobile does not have the edit button

**Comment by dmitryd** [comment]
> Currently that value needs to be forever in the decode / encode caches which is even worse

Incorrect :)

**Comment by AndreasA** [comment]
Yes because it contains more information than just a hash over the relevant chash parameters which is just a few bytes

But if you intend to use the current solution at least rename the tables.

**Comment by dmitryd** [comment]
> But if you intend to use the current solution at least rename the tables.

Not worth the time spent on renames, code adaptations and migration wizards.

**Comment by AndreasA** [comment]
The I thin a separate table that only stores a hash of valid relevant hash parameters as hlehum mentioned would be a good idea because caches are supposed to be temporaray data that upon deletion only sloelw down the system and not result in possible errors.

I think the "best" would probably be to have speaking urls in the core that e.g. stores uniqe alias to a any table and only allows access via speaking url to that parameter.

Actually if one only has lookup table parameters one could verify if the parameter is valid prior to new chash generation.

**Comment by helhum** [comment]
> who think that it is not a vulnerability but a valid and useful feature

I'm sorry, but ignoring facts does not make the issue go away.

State without this realurl "feature": 
no arbitrary cache entries can be created by attackers

State with this realurl "feature":
arbitrary cache entries can be created by attackers

Are you really denying these facts?

**Comment by AndreasA** [comment]
@helhum: regarding your suggestion you mean to get the rekevant chash parameters, create hash for those, store hash in separate table (that is not called cache_*) and on decode create hash of chash relrmevant parameters and check if that hash is in the table? If so calculate correct chash else do nothing. 

If so I think it would be a good solution for now as that table really shouldn't become too huge

**Comment by dmitryd** [comment]
@AndreasA No, it will become huge. It is exactly v1 way and I will not make same mistakes again.

@helhum It does not seem that you are interested in the real solution. Looks like you want me to make another workaround that will have side effects. I already had that in v1. Not going to repeat it. Unless there is support from the core, which I outlined above, this cannot be properly solved.

**Comment by dmitryd** [comment]
Anyway, I think we discussed enough here. We just repear same things again and again. I consider the issue closed because the option is off by default and there are multiple warnings about problems that will happen if it is on. So it is closed for me.

**Comment by AndreasA** [comment]
But now the cache tables will get huge because you can never know if the URL with those parameters is still in use, the same as with storing the cHash in a different table.
You might be able to clean it if you rename a page or similar but if records are deleted or similar you will have the same issue with cleaning it.

One idea in regards to a own cHash table would be quite simply to add a field lastUsed and if it wasn't used for e.g. a configurable time it could be automatically deleted by e.g. a scheduler.

**Comment by dmitryd** [comment]
> But now the cache tables will get huge because you can never know if the URL with those parameters is still in use, the same as with storing the cHash in a different table.

No, this is incorrect. Realurl handles that already since about 4 years.

> You might be able to clean it if you rename a page or similar but if records are deleted or similar you will have the same issue with cleaning it.

No issues. Realurl already handles this too.

**Comment by dmitryd** [comment]
> One idea in regards to a own cHash table would be quite simply to add a field lastUsed and if it wasn't used for e.g. a configurable time it could be automatically deleted by e.g. a scheduler.

Yeah, I already got complaints that realurl does too many updates of tstamps on cache tables, so this feature was removed and speed got better. Not brining those updates back.

I am thankful for all those suggestions but all these things are either exist or were tried and got rejected.

**Comment by AndreasA** [comment]
> No, this is incorrect. Realurl handles that already since about 4 years.
And how / where does it handle this?
For instance I can have a parameter, that just rewrites xyz=X&cHash=foo to xyz/X/
which you can never track if the URL with that parameter is used or not because the parameter can be anything that just makes sense in combination for the plugin.

Also regarding cHash and caches: Isn't it currently possible to clear the URL cache by using the speaking URL module which would also remove the cHash?

**Comment by helhum** [comment]
Dmitry, what do you mean wit "real solution"?
You you mean the core changes, that you claim to have in mind?

I'm happy to implement them, but you would have to be more verbose. Just saying that you solved it all, will not change anything. You at least need to offer a detailed concept. 

If the "real solution" is vulnerable code, I will just stop arguing and avoid that code.

**Comment by dmitryd** [comment]
@AndreasA You are welcome to study realurl code to get answers to all your questions.

@helmum I do not want to argue. I spent enough time in this thread and on realurl in general to continue the same discussion again and again. I suggest to stop here. There are other things in life that deserve time...

**Comment by dmitryd** [comment]
Oops, sorry for the typo :(

**Comment by AndreasA** [comment]
As mentioned I checked and yes there is an expire and clear cache function but as mentioned in the code it only works for pages - and you won't get all possible parameters here or am I missing somewhere where the urlcache is expired / cleared because realurl parameters do not exist anymore?
Of course, mostly in that case the corresponding page has been removed too so that works but that must not necessarily be the case, e.g. I could just swap a plugin for another on the same page.

Also as mentioned  'cache/disable' will disable caching and therefore cHash won't be stored at all.

And then there is the backend module that allows one to clear the Url-Cache but with the cHash change due to 2.0.15 one cannot do so anymore without "consequences".

**Comment by dmitryd** [comment]
> And then there is the backend module that allows one to clear the Url-Cache but with the cHash change due to 2.0.15 one cannot do so anymore without "consequences

Yes, this is one of reasons why chash calc was there since the beginning. For the rest you can search the code more.

**Comment by AndreasA** [comment]
1.) You said you had problems with people asking question why things didn't work correctly due them e.g. deleting cache tables with the current solution you are back to that "issue".

2.) I agree that with the previous method everything was fine in regards to caches.
With the current it isn't anymore as they contain necessary information.
And I also I agree that I would prefer to generate the correct cHash upon decoding always but 
due to helhum we know that creates a possible DoS attack so there needs to be a better solution.
Which is why I still think the solution idea from helhum has merrit.

It only generates a hash if realurl is allowed to generate the cHash on its own during decode, nothing more.
Also: Nothing prevents you from cleaning up that table the same way you clean up the current urlcache / pathcache.
For instance you can store a page id with it and use that to cleanup the table if a page is deleted.
You could store further meta data in a separate table like which records are used (and which parameters to remove the values if the parameters don't exist in realurl configuration anymore) etc. to clean it by DataHandler hook or scheduler task (as in the backend performance isn't that big an issue)

If one goes with the 256 bytes due to overhead that helhum mentioned you would need over 4 million entries to reach one gigabyte.
If you achieve that many you will run into the same problem by adding the cHash to the current encode/decode cache,.

3.) I checked the code more and:
So you are taking care of various page cache clearing by using clearCachePostProc and some via DataHandler hook that checks for unique aliases.
However, that also means that cHash information is removed upon cache clearing due to e.g. set clearCacheCmd 
Or you clear the urlcache for a whole page id, if any language record was deleted which results in cHash values being lost of other languages too.
Also there can be other parameters that are not stored in unique aliases.

The issue now is just that we are storing necessary data cHash into tables that are not supposed to be necessary (cache)

**Comment by AndreasA** [comment]
I just saw that you renamed those tables which is great that way people will not just delete data that might be necessary.

**Comment by dmitryd** [comment]
Please, don't post entries like this to the bug tracker because they only loose my time and do not add any value to the product.

**Comment by AndreasA** [comment]
OK. Sorry but it was related to my previous comments so...

**Comment by Chrissitopher** [comment]
The following fix has been merged in TYPO3 6.2, 7.6 and in master: https://review.typo3.org/#/c/49925/.

Setting ``[FE][cHashIncludePageId] = true`` will now enable some kind of cache flooding protection. This setting is set to ``true`` for new installations. It is ``false`` for existing installations, but the reports module will warn users and advise them to manually set it to ``true``.

**Comment by dmitryd** [comment]
Yes, I am aware of that. It will solve issues for those, who still use 2.0.14.

**Comment by helhum** [comment]
> It will solve issues for those, who still use 2.0.14.

Uhm, no. With `[FE][cHashIncludePageId] = true` realurl 2.0.14 will cause an exception to be thrown. Thus 2.0.15 is the only realurl release, that will work (with the [exceptions](https://github.com/dmitryd/typo3-realurl/issues/244#issuecomment-245849106) from above) in that case.

**Comment by dmitryd** [comment]
Okay, good to know. I expected it to work. @helhum If you already tested it, do you have exception text under hand (no problem if not, just wondering what the exception is).

**Comment by helhum** [comment]
The problematic lines in realurl are these: https://github.com/dmitryd/typo3-realurl/blob/bb47c65bd38489e6fe910685331b8b55ac1d2165/Classes/Decoder/UrlDecoder.php#L156-L159

And this exception will be thrown: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/Page/CacheHashCalculator.php#L131

Reason is, that cHash calculation will then require the id argument to be passed to `\TYPO3\CMS\Frontend\Page\CacheHashCalculator::getRelevantParameters`

**Comment by AndreasA** [comment]
Which is not done because doDecoding does not add the 'id' to the $requestVariables.

Also I think it doesn't really fix the bugfix of 2.0.15 in 2.0.14 because one could still create arbitrary arguments.

Also in UrlEncoder for storeInUrlCache there i a comment that says:
// $this->originalUrlParameters['uid'] can be an alias, we need a number here!

which might also create troubles?

**Comment by dmitryd** [comment]
@helhum Thanks! So I should modify the code to add 'id' there if I use cHash calculator...

**Comment by AndreasA** [comment]
As far as I understand:
Only if "id" is part of the relevant variables (the corresponding setting) is set. So adding it to the requestvariables before going into the relevant parameters should fix it.

**Comment by AndreasA** [comment]
Btw. I forgot to ask when using the current development or 2.0.15 and use bypass variables can that create problems in regards to cHash and v2.x
I knew it sometime created problems with v1.x because the same URL could be accessed with different parameters (both URLs were valid). 
But I guess because the request_parameters are now stored with the URL that should work fine?

**Comment by Chrissitopher** [comment]
> So I should modify the code to add 'id' there if I use cHash calculator...

Yes, that is also what the [security bulletin](https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2016-022/) advises:

> Additionally, calling the CacheHashCalculator API will require the id argument to be set in the URL provided. This means, that switching this option on, may break existing extensions, that are using this API.

**Comment by helhum** [comment]
> the bugfix of 2.0.15

@AndreasA What bugfix of 2.0.15?

**Comment by dmitryd** [comment]
FYI: I am not receiving notifications in this thread anymore because it makes too much email noise.

**Comment by helhum** [comment]
I unsubscribed as well now

**Comment by AndreasA** [comment]
Meant the one regarding storing cHash instead of calculating it - the reason for 2.0.15 release (security issue).

**Comment by MirekKmiec** [comment]
For tt_news fix:
`plugin.tt_news {
	allowCaching = 1
}`
