### ISSUE TITLE
[BUG / FEATURE] cHash with version >= 2.0.15 and non database cache (using cacheImplementation)

### ISSUE THREAD

**Issue by AndreasA** [dmitryd/typo3-realurl#249]
Due to the very useful option  $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['realurl']['cacheImplementation']
one cannot override the cache implementation to use e.g. memory cache, APC, Redis, etc.
Which is a nice feature as those caches might improve performance.

However due to security change with 2.0.15 in the handling of cHash those won't work correctly anymore as they are not persistent, e.g. a server restart will clear most of them.

Which is why I propose again to use a own way to store the cHash and just clear it correctly when deleting normal page tables.

However, the propose solution to just stored hashes of allowed relevant parameters could also be done but using touch and file_exists to create a file and check if it exists instead of an own table if you still fear of the table getting too huge. That way there never should be any big files. Could be an optional setting.

**Comment by dmitryd** [comment]
> Which is why I propose again to use a own way to store the cHash and just clear it correctly when deleting normal page tables.

I already wrote "no". It opens a DoS vulnerability. The discussion about it is closed.

**Comment by dmitryd** [comment]
Previous comment is removed because it is not accurate.

I will not add a separate cHash storage because it will open the same set of problems that could not be solved in v1. Those problems were very hard for many high-profile customers from various countries. Realurl v2 was specially designed to avoid those problems. I am developing realurl for many years. Firsts, I fixed bugs, than refactored, than increased performance. I also had to work with lots of customers to solve their issues with realurl. So I know the topic much better than anybody else. Therefore I will not repeat the same mistakes that were done once already.

For me the discussion about it is closed unless somebody finds a bulletproof way to control cHash storage. I do not see such way.

Regarding cacheImplementations: it will be either set to "internal" or will go "undocumented, use at your own risk" or will cease to exist with 2.1.0. I am not sure yet. I wanted to remove it yesterday but decided to think more.

If you really want to do something useful, go and fix some other issues (make a PR). For example, #193 or #195. That will be much better contribution than forcing me to explain the same thing for the Nth time.

**Comment by AndreasA** [comment]
Ok. From what I understood one of the problems was that the chash table could get big but you could just clear it along with pathcache/urlcache which should resolve that problem, shouldn't it?
But I guess it would be a lot of extra work?

In regards to cacheimplementation: 
What about the followibg idea:
You could use it in addition to DatabaseCache.
Like store values there and in databasecache.
That way decode could use apc etc. as long as those values exist there. If not it can still fallback to databasecache. And restore them in apc etc.

However maybe it is enough if the custom cache implementation does that by extendong databasecache and calling the parent fubctions
