### ISSUE TITLE
Cache-problem with postVarSets on detail-pages

### ISSUE THREAD

**Issue by bihor** [dmitryd/typo3-realurl#263]
When I use this with realURL 2.0.15:
`'postVarSets' => array(
  '_DEFAULT' => array('news' => array(
	array(
			'GETvar' => 'tx_news_pi1[action]',
	),
	array(
			'GETvar' => 'tx_news_pi1[controller]',
	),
	array(
		'GETvar' => 'tx_news_pi1[news]',
	),
  ),),
),`
then I get a correct link, but I get for every detail-page the same content on the page.
That is a cache problem.
This code worked with realURL 1, but why doesn´t it work with version 2 correct?
Example:
/meldung/news/detail/News/210.html
/meldung/news/detail/News/217.html
The links are OK, but with the second link I get the same content like with the other link.
I tested it in 2 different webs with TYPO3 6.2 and 7.6...

**Comment by macjohnny** [comment]
this is related to 
* https://github.com/dmitryd/typo3-realurl/issues/244
* https://github.com/dmitryd/typo3-realurl/issues/252
and we are facing exactly the same problem.

the problem is, that if a backend user is logged in, realurl does not use the urlcache.
the result is that a url needs to be decoded from the query string, but since it does not include a cHash, this won't work.
See https://github.com/dmitryd/typo3-realurl/blob/master/Classes/Utility.php#L92

This seems to be changed in the current development version

https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Utility.php#L120

**Comment by dmitryd** [comment]
Help is not provided in the bug tracker. This place is only for actual confirmed bug reports.

**Comment by macjohnny** [comment]
@dmitryd why not just add a label "question / comment"?
github is a platform that makes it easy for people to interact and contribute. 
i doubt people new to typo3 projects find it easy to handle forge.typo3.org and gerrit...
that's a pitty, this way a lot of potential contributions are lost.

**Comment by macjohnny** [comment]
and just by the way: this issue actually is a real problem that we also had and required quite some debugging. so we are not happy with the change introduced in 2.0.15 either...

**Comment by dmitryd** [comment]
Each project has its own rules. This project does not allow questions in the issue tracker. See [Bug reporting](https://github.com/dmitryd/typo3-realurl/wiki/Contributing#bug-reporting). There are several simple reasons:

1. This is a free project, so there are no requirements for me to offer support.
1. There are other channels where people can get support (see [Getting help](http://github.com/dmitryd/typo3-realurl/wiki/Getting-help))
1. It takes a lot of time to process entries here due to the complexity of realurl. I have very limited time for this project and want to spend this time for development and bug fixing.

Therefore there will be no questions/answers here.

> i doubt people new to typo3 projects find it easy to handle forge.typo3.org and gerrit...

And can't people see what's written on the project page?

<img width="677" alt="wiki" src="https://cloud.githubusercontent.com/assets/306133/18666734/6f94c978-7f3e-11e6-83d2-7b504ca2245b.png">
