### ISSUE TITLE
No Backend-Modul in TYPO3 6.2

### ISSUE THREAD

**Issue by hirnsturm** [dmitryd/typo3-realurl#289]
After installing realUrl version 2.0.15 in TYPO3 6.2 is no Backend-Modul available.

**Comment by dmitryd** [comment]
By design. This will not change.

**Comment by dmitryd** [comment]
Just a bit more explanation, since I have time. 7.6 and 6.2 are different in the way how Extbase makes BE modules. Since 6.2 is quite old already, I preferred to focus on the version, which was most used at that moment (7.6) and also on development of the frontend part and fixing issues. Now 6.2 is getting older and older, so I believe it is not worth investing time into it unless I have absolutely nothing else to do.

I hope it explains the previous short notice better.
