### ISSUE TITLE
Realurl struggling to decode unicode characters

### ISSUE THREAD

**Issue by rickymathew** [dmitryd/typo3-realurl#310]
I've been using realurl v2.0.15 in my TYPO3 website which manages multiple domains with numerous language configurations, including non European too. Everything was working fine until I'd recently updated extension to v2.1.4 stable release.

The new version seems like not working well with non european languages like Chinese, Taiwanese etc. Realurl is not completely encoding these Unicode characters in the URL

my site url, before upgrade : www.mysite.cn/主页/新闻/展会与活动

after upgrade : www.mysite.cn/%2F%E4%B8%BB%E9

and the view is resulting in a page not found error. Meanwhile European ASCII characters are getting encoded well and working as expected.
I've tried the configuration inside realurl_conf.php by setting 'enableAllUnicodeLetters'=>true and is still not working.

**Comment by dmitryd** [comment]
I just tried using those characters as a page title. Here is what I got in html:

<img width="778" alt="chinese-characters" border="1" src="https://cloud.githubusercontent.com/assets/306133/19850535/09695dde-9f6a-11e6-9d36-aabf7eab5fda.png">

The issue is not reproducible here :(

Option `enableAllUnicodeLetters` does not exist in realurl. Realurl 2.x always handles unicode letters for URL.

**Comment by dmitryd** [comment]
Just checked HTML using curl to avoid any browser changes or renderings. Here is what I got in my terminal:

```html 
<li><a href="http://typo3_7-6.dev/主页新闻展会与活动.html" title="主页/新闻/展会与活动">主页/新闻/展会与活动</a></li>
```

**Comment by rickymathew** [comment]
i'm using English as first translation . But have set Chinese as default language via typoscript.That's why this happens.Is there any way to bypass the problem without using Chinese as first translation in backend?

**Comment by dmitryd** [comment]
You have to ask such questions elsewhere. This place is for realurl bugs only.

**Comment by AnuBN** [comment]
k

**Comment by AnuBN** [comment]
I've faced the same issue in my website, after upgrade to realurl v2.1.4 . My typoScript configs are correct I guess. Because everything was working pretty fine untill the update.

www.mysite.cn/%2F%E  -> translation to ASCII seems to be incomplete.

**Comment by adrienjacob** [comment]
I noticed that none of the pages in the non ascii languages we use (Japanase, Chinese, Korean, Cambodian) were finding cache entries properly. This is because $speakingUri is encoded, while cache database entries have decoded values... So I added this on line 157 of UrlDecoder.php (before calling runDecoding) :
`$this->speakingUri = urldecode($this->speakingUri);`

**Comment by dmitryd** [comment]
Should be ok now.
