### ISSUE TITLE
fixedPostVars need to be fully matched

### ISSUE THREAD

**Issue by liayn** [dmitryd/typo3-realurl#318]
If a fixedPostVarSet is only partially matched on decoding, the input is currently accepted and the requestVariables are created. This is in our opinion a big issue, since this will cause duplicate content problems as two urls will point to the same content.

Example:
A fixed postvarset is configured to have news records shown as `/year/title`, like `example.com/2015/news-title`. The root page is configured to display the news detail view if a news is provided via GET.
Calling the page `example.com/` alone delivers the homepage with a 200 status code.
Calling the page `example.com/asdf/` delivers the exact same output as above, also with a 200 status code.
This is a no-go.

`\DmitryDulepov\Realurl\Decoder\UrlDecoder::decodeFixedPostVars` contains a
```
// TODO Is it correct to break here? fixedPostVars should all present!
break;
```

I would strongly suggest that this is **not** correct here.
All variables have to be set of a fixedPostVarSet, otherwise no other logic has a chance to detect the malformed URL.

The pull request would be really easy ;-)

**Comment by dmitryd** [comment]
The comment you mentioned is my user/author dilemma. Realurl 2.x is compatible with 1.x in this behavior, so I cannot really break it. As a user I fully agree with you but as the author I cannot break other existing sites that rely on this functionality. And I know that such sites exist.

Generally you should design your URL structure in a way that does not allow such issues. Realurl cannot be too clever because it is a hack on top of TYPO3. The simpler your URLs are, the better. By "simpler" I mean that they should not be too clever. Ideally you should have a dedicated page for news single view. I know this is not always desired but than realurl is also very complex and it cannot solve absolutely every problem and use case.

I do not think this can be enabled **by default**. However, this can be done with a configuration option. Something like `init/fullFixedPostVarEvaluation` or a better name.

**Comment by dmitryd** [comment]
Example of a fixedPostVar with variable number of parameters:

/path/to/detail/page/my-info-item-title/
/path/to/detail/page/my-info-item-title/mark-unread/

The first one is a `lookUpMap`, the second one is a controller action with `noMatch=bypass` and `mark-unread` equals to `markUnread` action. That one is used in a project I know.

**Comment by liayn** [comment]
Yes, an option to enable this check would be totally enough for me. I would even make that option per set and not globally.
I'll prepare a PR for that.

**Comment by liayn** [comment]
Regarding the example above. If a `bypass` is used, this is still a full evaluation IMO.

**Comment by dmitryd** [comment]
> Regarding the example above. If a bypass is used, this is still a full evaluation IMO.

Evaluation will stop if there are no more segments. This is exactly what that removed code does. So `bypass` will not be even checked.

**Comment by liayn** [comment]
@dmitryd I updated the patch to include the option now. This version works perfectly already in production.

**Comment by liayn** [comment]
args... one more issue

**Comment by liayn** [comment]
here we go
