### ISSUE TITLE
Exclude from speaking URL does not work

### ISSUE THREAD

**Issue by dr2okevin** [dmitryd/typo3-realurl#322]
Tested with TYPO3 7.6 and RealURL 2.0.14 and 2.1.5
I have some Pages (No News or other plugin pages).

My Tree
```
* ROOT (id=0)
|- Home (Page, starting point)
 |- Menus (Menu Seperator, Exclude from speaking URL)
  |- Menu-A (Menu Seperator, Exclude from speaking URL)
   |- Contact (Page)
   |- Company (Page)
  |- Menu-B (Menu Seperator, Exclude from speaking URL)
   |- Terms (Page)
```

Expected URL
/contact
/company
/terms

Actual URL
/menus/menu-a/contact
/menus/menu-a/company
/menus/menu-b/terms

I can reach the pages manually if I type the expected url.

**Comment by adrienjacob** [comment]
Same problem here on 6.2.29 and RealURL 2.1.5, and different kind of items (not only menu separators, but normal pages or folders). Truncating RealURL tables solves it, but then any change in the "exclude from" parameter is not taken into account, unless we truncate again. So there seems to be a caching issue (the old url is used instead of the new one).

**Comment by adrienjacob** [comment]
And the same issue occurs for the "Override the whole page path" parameter.
"Speaking URL path segment" looks ok.

**Comment by wkrawczak** [comment]
Is there any progress on this? We have also encountered this problem. I would be glad to try preparing a patch, if someone could point me in the right direction (which files I should look for the bug in).

Tanks.

**Comment by adrienjacob** [comment]
I believe I found a solution in this other thread #367 (forgot this issue was already mentioned here)
Being a total Github newbie, I haven't done a Pull Request yet. I will probably do it later on.

**Comment by smoebody** [comment]
Also i have a problem that the UrlEncoder stores pages which are explicit excluded from realurl in urldata cache table. is this expected behavior and if yes, can anybody tell me why?
backround is, that we have link-pages with same name and same hierarchy level as the linked pages (don't ask me why, im not responsible for that). 
```
_
 \
 - id=100: Locations (Link to id:101, excluded from realurl)
 - id=101: Locations (actual page)
...
```
anyways i did set the 'exclude-from-realurl' flag in the link-page but its still saved to urlcache and pathcache tables and therefore the UrlDecoder gets the page from cache which is obviously wrong unless i missed something.
