### ISSUE TITLE
it generates urls to non-existing languages

### ISSUE THREAD

**Issue by jmtpix** [dmitryd/typo3-realurl#358]
I use realurl 2.1.5 and typo3 7.6.13.
The standard language (0) is german and I've just added one additional language in the backend (1 => en).
Now realurl creates links with the language UID 2 - but this language does not exist.
Here is a Screenshot of the generated URLs and the pathdata from one Subpage:
![Screenshot of Realcache](http://www.pixelrausch.info/download/realurl.jpg)

And here's my realurl configuration script:
```
$TYPO3_CONF_VARS['EXTCONF']['realurl'] = array(
 '_DEFAULT' => array(
		'init' => array(
			'appendMissingSlash' => 'ifNotFile',
			'enableUrlDecodeCache' => 1,
			'enableUrlEncodeCache' => 1,
			'postVarSet_failureMode' => '',
		),
		'redirects' => array(),
		'preVars' => array(
			array(
				'GETvar' => 'L',
				'valueMap' => array(
					'de' => 0,
					'en' => 1,
				),
				'valueDefault' => 'de',
				'noMatch' => 'bypass',
			),
			array(
				'GETvar' => 'no_cache',
				'valueMap' => array(
					'nc' => 1,
				),
				'noMatch' => 'bypass',
			),
		),
		'pagePath' => array(
			'type' => 'user',
			'userFunc' => 'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
			'spaceCharacter' => '-',
			'languageGetVar' => 'L',
			'expireDays' => 7,
			'rootpage_id' => 1,
			'firstHitPathCache' => 1,
		),
		// configure filenames for different pagetypes
		'fileName' => array(
			'defaultToHTMLsuffixOnPrev' => 1
		),
	),
);
```
In Typoscript i set the following options for the standard language:
```
config {
sys_language_uid = 0
    language = de
    defaultGetVars {
        L = 0
    }
}
```
I've tried and searched for the mistake, but I can't find it.
Do you have any ideas, where realurl finds the language uid '2'?

**Comment by spillse** [comment]
Hello together, we made an even worth discovery with latest realurl version (2.1.5):

If a website is called with unused/wrong GET parameters (e.g. old parameters, parameters from automated hacking attempts,...), these get saved/cached in tx_realurl_urldata table. This leads to the problem that wrong parameters are used to generate the website. Here is one example:

<img width="780" alt="screenshot at dez 13 21-06-27" src="https://cloud.githubusercontent.com/assets/4367745/21157157/b9b517e8-c178-11e6-95a6-6009773de87e.png">

There was an ' character added to the url by trying to do sql injection. This leads to the behavior, by calling the website with url http://www.domain.com/en/about-us.html, the wrong language (default, L=0, German) is used for frontend ouput instead if the correct one (L=1, Englisch).

I hope there is a quick solution to solve this issue, because currently the only way is to clear realurl cache and frontend cache every few minutes. Otherwise the website could output the wrong language.

Best regards,

Sebastian

**Comment by dmitryd** [comment]
@spillse Your message is not a bug but incorrect configuration on your side. You need to go and read TSRef. Realurl encodes URLs exactly as is. What you see is the result of your TypoScript, which allows arbitrary values in `L`. If I remember correctly, the option to disallow such values was introduced in TYPO3 4.5.

@jmtpix This place is not for asking questions. This place is only for confirmed bugs. See "Getting help" in the wiki.

**Comment by dmitryd** [comment]
Btw, if you deactivate realurl completely, you will have wrong values in your `L` anyway. So not a realurl problem.

**Comment by spillse** [comment]
Problem was fixed by typoscript configurtion and limit L params to specific allowed values.

Thank you!
