### ISSUE TITLE
RealURL not working if page title begins with a number

### ISSUE THREAD

**Issue by angeloprevitali** [dmitryd/typo3-realurl#363]
If a TYPO3 CMS page title name begins with a number RealURL 2.1.5 with TYPO3 CMS version 6.2.29 gets an error.

**Comment by ayacoo** [comment]
Can you please add the error message for this error? Or a screenshot...

**Comment by angeloprevitali** [comment]
If a title/menu name is i.E. 10.Ausbildung RealURL wthrows an Error - Page not found. If you rename the same menu like 10Ausbildung everything works. So, that problem leads on the following: 
- A Number followed by a point in the title of the menu throws an error.
Can you reproduce this, too?

**Comment by dmitryd** [comment]
> RealURL throws an Error - Page not found

RealURL does not throw such errors. Are you sure it is an error from RealURL?

For now I close the issue because I believe it is not related to the realurl. If you are absolutely sure, post your ideas here and I may reopen the request.

Please, remember that this is place is only for bugs that you can confirm are causes by realurl.
