### ISSUE TITLE
404 after rename page and create a new one with same name

### ISSUE THREAD

**Issue by SventB** [dmitryd/typo3-realurl#373]
I get a 404 error after renaming a page and creating a page with the same name again (TYPO3 7.6.15, realurl 2.1.5).

You can reproduce this easily:
* Create page "realurltest1" (reload frontend after every step, so realurl database entries are created)
* Rename this page to "realurltest2"
* Create new page "realurltest1"

Now you have two entries in table "tx_realurl_pathdata" with the same "pagepath" and when opening url "realurltest1" in frontend, you will get a 404 error.

**Comment by macjohnny** [comment]
@SventB we have the very same issue here, too.

**Comment by mvoehringer** [comment]
We also see this problem. In the tx_realurl_urldata table i found the following records for the page:
![screen shot 2017-01-20 at 13 54 35](https://cloud.githubusercontent.com/assets/2719466/22150201/15f19f92-df18-11e6-9895-a6f26796486d.png)

After deleting the first (expired) record, the 404 is gone.

**Comment by macjohnny** [comment]
@mvoehringer we found similar records in our database. unfortunately, the expiration time has no effect. 

i think the problem should be treated when deleting a page.

**Comment by mvoehringer** [comment]
@macjohnny Have you tried the latest GIT version of real-url? I found an bugfix https://github.com/dmitryd/typo3-realurl/commit/cb3b2fe5ed725b2b3f6586443f99306ec1a8e0a2

that sounds like it fixes our problem. This Bugfix is not jet released.

**Comment by macjohnny** [comment]
@mvoehringer i have only tried the latest official release, i.e. 2.1.5
the bugfix would resolve the problem after some time, but the problem would still persist until the old record expires.

**Comment by mvoehringer** [comment]
I have tested the latest Git (developer branch) version and can't reproduce the problem.

**Comment by houmark** [comment]
I think a similar issue can happen when you delete a page and create a new page with the same name as the deleted page. Somehow realurl seems to get to the deleted page and since that page is deleted, the result is a 404.

If you rename the new non-deleted page to something slightly different, it works just fine. The same, if you go directly to the database and rename the deleted page to something else, it works.

The above is based on trial and error testing on the TER version. I will try to check out the latest Github version to see if cb3b2fe fixes this situation as well.

**Comment by adrienjacob** [comment]
I believe I found a solution to this problem, which also solves issue https://github.com/dmitryd/typo3-realurl/issues/385, and maybe also https://github.com/dmitryd/typo3-realurl/issues/329.

After having a look at DatabaseCache.php, I realised a query was performed to get cache entries, and sorted results by ascending expire value. The loop starting here https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Cache/DatabaseCache.php#L203 is supposed to stop as soon as a match is found in the cache.

The problem is: in my situation it was always returning the last occurrence, ie. the cache entry with the highest expire value (which shouldn't be the case, if another match exists with expire=0 for example).

I believe this is because of the condition on lines https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Cache/DatabaseCache.php#L210 and https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Cache/DatabaseCache.php#L223. In my setup (maybe that's a particular one but I see it's the same in the example above), I don't have any chash values in variables, so the condition was always wrong... For now I just removed the condition, and the problem(s) is solved.

As I'm not sure what this condition was supposed to do in the first place, I won't commit it now. But I'm curious to have your feedback on this.

**Comment by houmark** [comment]
@adrienjacob Nice work there. I think that fits with our issue as well, so I will attempt to make a test with your findings in mind as soon as I can find some time to get around to it.

**Comment by adrienjacob** [comment]
In fact it seems the problem was already fixed (a bit differently) on the development branch with commit https://github.com/dmitryd/typo3-realurl/commit/cb3b2fe5ed725b2b3f6586443f99306ec1a8e0a2, so the latest TER version should already solve the issue !

**Comment by macjohnny** [comment]
as far as I have tested it, this issue is solved in version 2.1.7. thanks!

**Comment by dmitryd** [comment]
related to #400

**Comment by dmitryd** [comment]
Okay, good to hear that it is solved :)
