### ISSUE TITLE
Double url encoding for ignored get parameters

### ISSUE THREAD

**Issue by stoppeye** [dmitryd/typo3-realurl#375]
The value of a parameter that is included in ignoredGetParametersRegExp can end up with double url encoding.
I've noticed that in removeIgnoredParametersFromQueryString() of class EncodeDecoderBase, the names of all query parameters, but only the values of parameters that are not ignored, get urldecoded. If all parameter values get urldecoded here, the double encoding problem went away in my use case.
I don't know what the reason was to specifically exclude those values from decoding. But if the reasoning was to leave ignored parameters "as is", then there shouldn't be any further processing (i.e. urlencoding) later on.

**Comment by dmitryd** [comment]
You are right, `urldecode()` was missing for those parameters.

It is necessary to have them decoded because later they are added back to the list of parameters and `GeneralUtility::implodeArrayForUrl()` is used for recreating the query string. This function encodes values. Thus all values must be unencoded.
