### ISSUE TITLE
changing page title does not delete the old cache entries

### ISSUE THREAD

**Issue by lisardo2** [dmitryd/typo3-realurl#385]
When a backend user names two pages with the same title both pages get the same path in the realurl cache tables. So only one of the two pages is accessable. When the user recognizies his fault he is not able to fix it: he can change the page title but not the wrong cache entry. The cache entry - and the false url - remains for 1 month in the database. Every week I get tickets like this from my users and have to delete them directly in the database. Well, or truncate the whole tables.

(TYPO3 6.2.30, last version of realurl 2).

**Comment by adrienjacob** [comment]
I confirm that's a very annoying issue... (occurred with same Typo3 / realURL versions)

**Comment by dmitryd** [comment]
> When a backend user names two pages with the same title both pages get the same path in the realurl cache tables. 

Read the docs (Limitation part).

**Comment by lisardo2** [comment]
I know that this is an error. But it occurs because shit happens and users aren`t perfect. I asked for a possibility to fix the error without truncating the tables.

**Comment by dmitryd** [comment]
Realurl cannot do that. Please, educate your editors. There are requirements that you really have to fulfil if you want to use realurl. There is no workaround in such case.

When you use the car you don't say "people can forget keys but still need to drive the car". This is just not possible. Same here. You have to ensure that there are no duplicate titles, otherwise realurl cannot work properly and its behavior is undefined.
