### ISSUE TITLE
Wrong "L" parameter value exception

### ISSUE THREAD

**Issue by joakim1** [dmitryd/typo3-realurl#407]
RealURL version 2.1.6 and 2.1.7 gives this error. Version 2.1.5 works fine.

![fg61w](https://cloud.githubusercontent.com/assets/5311751/22935277/6a14728e-f2d2-11e6-95bd-a7ba0ed21571.png)

**Comment by mgrn0** [comment]
We have the same problem here. Weird thing is that a url works *almost* all the time, however it may fail anytime later, giving this exact error.
![2017-02-15_09-29-04](https://cloud.githubusercontent.com/assets/3019226/22966177/565b069c-f361-11e6-9e00-dca58ddbb354.jpg)

**Comment by ulrikkold** [comment]
I saw rows with an L-parameter with values 0, 1 and 01 in the database. After truncating the tx_realurl_urldata (and Dmitry is likely going to mention now, how that is _really_ not necessary) the problem disappeared.

**Comment by birgerstoeckelmann** [comment]
Hello! 

This bug is even worse and destroyed one of our sites: Calling a website with an invalid language parameter (e.g. ?L=9) an exception is thrown! We configured config.linkVars properly with config.linkVars = (0-3).

The wrong path is written into the tx_realurl_pathdata cache - so the next time the page is called with a correct speaking url the exception is thrown, because the last entry with L=3 is used.

Rollback to 2.1.5 and do not use the newest version for now.

**Comment by vandres** [comment]
We have a similar problem. We create the urls for the default language without the language code in the url by using `typolink.additionalParams = &L=`. This seems not to work anymore and throws the error the others mentioned.

**Comment by dmitryd** [comment]
This check was introduced because of other bug reports about wrong `L`. TRo avoid it you have to make sure that your links include correct `L`. You can achieve with two things (both are must):
1. Use `config.linkVars = L(0-5)`, where `0` to `5` is your valid range of languages
1. Avoid `typolink.addQueryString` completely or use `typolink.addQueryString.exclude = cHash,L` because `addQueryString` bypasses `config.linkVars` check. Basically it means that if you have `typolink.addQueryString` anywhere (some fluid viewhepers use it, for example), you allow **arbitrary parameter values** into your urls, which not just makes bad `L` but also creates security risks for your web site.

I am generally against such checks and exceptions. But people constantly request that realurl should store only valid values in the cache. I am tired of saying that realurl just encodes what it gets from TYPO3. So I added this check as people wished. As you see, I was right when I resisted it before. Now it "ruins" some sites. Well, I'd say those sites contain security flaws and you have to fix them ASAP.

**Comment by birgerstoeckelmann** [comment]
We configured config.linkVars properly with L=(0-1). But you can break the site with external calls (like hacker scripts or robots iterating the L parameter).
The wrong value (e.g. ..&L=9) throws the exception BUT the url is written into the tx_realurl_pathdata cache for the default language. 
Calling later the page with speaking url the site breaks, because realurl decodes to the wrong url with L=9.

**Comment by dmitryd** [comment]
> The wrong value (e.g. ..&L=9) throws the exception BUT the url is written into the tx_realurl_pathdata cache for the default language.

This is my part to check. But your part is to make sure that `L=9` does not even come to realurl. Let's do each own's part well.

**Comment by dmitryd** [comment]
> BUT the url is written into the tx_realurl_pathdata cache for the default language.

This does not see right because the exception is thrown before the encoding starts. Stack trace:

1. [Encoder::validateLanguageParameter()](https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Encoder/UrlEncoder.php#L1377)
1. [Encode::setLanguage()](https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Encoder/UrlEncoder.php#L1242)
1. [Encoder::executeEncoder()](https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Encoder/UrlEncoder.php#L874)

And path generation happens [below](https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Encoder/UrlEncoder.php#L880) the last stack entry.

So it does not look like wrong entry can get to the cache. Do I miss something in my analysis?

**Comment by dmitryd** [comment]
> We configured config.linkVars properly with L=(0-1). But you can break the site with external calls (like hacker scripts or robots iterating the L parameter).

Normally this should not happen because page generation should be aborted. But I found the case when content object exception handler silences the exception. I will make a workaround to prevent it.

**Comment by dmitryd** [comment]
@vandres 
> We have a similar problem. We create the urls for the default language without the language code in the url by using typolink.additionalParams = &L=. This seems not to work anymore and throws the error the others mentioned.

Why don't you [configure languages as realurl expects](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#configuring-languages) and use `&L=0` there? It is always better to have cleaner solutions.

**Comment by hannesbochmann** [comment]
I have the same problem on a site without any additional languages. Is it nevertheless necessary to configure something like config.linkVars = L(0) for a single language environment? This would seem strange.

**Comment by dmitryd** [comment]
@hannesbochmann It is necessary not to pass any `L` to links in such case. Your site does.

**Comment by gionkoch** [comment]
I also get the error, but everything seems to be configured correctly. This happens for the detail view of the tx_news extension:
`config.linkVars = L(0-5)`

request variables:
`{"id":"43","L":"3","tx_news_pi1[news]":"12141","tx_news_pi1[controller]":"News","tx_news_pi1[action]":"detail","cHash":"8814ba2c9aa75c9c24cc47f5fbfb8731"}`

Is it probably connected to having the same alias in another language?

en/detail/super-news
fr/detail/super-news

**Comment by dmitryd** [comment]
> Is it probably connected to having the same alias in another language?

No, this function only checks that L value fits into languages defined in TYPO3.

I probably need to show what links was wrong there...

**Comment by dmitryd** [comment]
@gionkoch You can try the current development version if you use composer name `dmitryd/typo3-realurl` and `dev-development` as a version. This should show you the wrong URL.

**Comment by gionkoch** [comment]
@dmitryd 
the URL in the exception has an empty L param:
`/index.php?id=43&L=&tx_news_pi1%5Bnews%5D=12192&tx_news_pi1%5Baction%5D=detail&cHash=3d179f9d692bba30f16c40d7b0358da4`

using the speaking url `/en/detail/sonova-presents-latest-innovations/` 
or with the L Param explizitly set
`/index.php?id=43&L=3&tx_news_pi1%5Bnews%5D=12192&tx_news_pi1%5Baction%5D=detail`
leads to the wrong L param exception.

My realurl conf looks fine aswell:
```
array(
'GETvar' => 'tx_news_pi1[news]',
	'lookUpTable' => array(
		'table' => 'tx_news_domain_model_news',
		'id_field' => 'uid',
		'alias_field' => 'title',
		'useUniqueCache' => 1,
		'useUniqueCache_conf' => array(
			'strtolower' => 1,
			'spaceCharacter' => '-'
		),
		'languageGetVar' => 'L',
		'languageExceptionUids' => '',
		'languageField' => 'sys_language_uid',
		'transOrigPointerField' => 'l10n_parent',
		'autoUpdate' => 1,
		'expireDays' => 180
	)
)
```

**Comment by dmitryd** [comment]
@gionkoch This means you have no language with uid=3 defined in your installation.

> using the speaking url /en/detail/sonova-presents-latest-innovations/

This is irrelevant because `L` is checked only when encoding.

**Comment by dmitryd** [comment]
I did some more improvements:

1. `L=` will now be accepted as a default language
1. Less information will be in FE but more in the web server error log. You will find a full stack trace there with function arguments, which will help you to find the cause of the wrong `L`.

**Comment by gionkoch** [comment]
Works again after the last fix, thanks @dmitryd

**Comment by dmitryd** [comment]
I have an idea to make a separate extension to pre-validate parameters. But no guarantees or promises :)

**Comment by droomdre** [comment]
I did all the above but still had the same problem. Be careful when using the extension "bootstrap_package". The Typoscript for the MenuProcessor calls differents languages. I had to change it to:
>  40 = BK2K\BootstrapPackage\DataProcessing\MenuProcessor
>             40 {
>                 special = language
>                 special.value = 0
>                 special.normalWhenNoLanguage = 0
>                 as = languagenavigation
>             }

Before it was 40.special.value= 0,1,2.

**Comment by adrienjacob** [comment]
That's right... in the latest version of bootstrap_package, you can also set in the constants `page.theme.language.languageValue = 0` (or whatever languages you use). Quite a few people had this problem I believe !

**Comment by dmitryd** [comment]
I still think we should only use values that are valid. You all know how many hacks happen recently. The less arbitrary values you have, the more secure you are.
