### ISSUE TITLE
UrlEncoder can't be executed from backend

### ISSUE THREAD

**Issue by paintsmultimedia** [dmitryd/typo3-realurl#422]
The UrlEncoder can't be executed from backend plugins, because in function canEncoderExecute there is a condition TYPO3_MODE == 'FE'.
Generating speaking url ist nessesary for extensions like varnishcache.

Is there any workaround for this?

**Comment by alappe** [comment]
Also blocks url generation in solr indexing of custom records… :-/

**Comment by dmitryd** [comment]
This can be removed but you need to know that realurl does not work properly in BE mode. It may cause exceptions and failures. This is why the condition was added.

Realurl requires a properly initialised FE environment. Some extension does not do that and cause errors in realurl. This is why this condition was added.

**Comment by alappe** [comment]
But introducing this in a minor update… hmm.

So I will need to stay on `v2.1.7` for the future, since a lot of custom and public extensions rely on this functionality.

**Comment by dmitryd** [comment]
> since a lot of custom and public extensions rely on this functionality.

A lot? :)

While this may work, the only guaranteed way when this will work correctly, is when `TYPO3_MODE == 'FE'`. Most likely I will revert this change but if anybody complains that realurl does not work for extension XYZ in the BE mode, this will be the problem of XYZ extension because realurl always expects FE mode and properly initialised FE objects.

**Comment by alappe** [comment]
Thanks!

**Comment by marvin-martian** [comment]
The reason for this change I believe can be found as a silent response to this discussion in issue #413 It is about the "right use" of realurl. Anyway thankyou for changing it back Dmitry.  :-)

As for realurl "not" working in the BE, there are some potential issues that could be improved to make it behave more elegantly (ala BEgetRootLine) . 

But the reason "requiring a properly initialised FE" is a seemingly non-issue via the BE other than a inconsistent TYPO3_MODE constant which may cause FE rendering inconsistencies if you rely on the TYPO3_MODE as a decision maker in your templates. Other than that, historically using realurl via the BE has "generally" been working for other extensions for quite a long time.

However maybe Dmitry is right, that it should be locked down to the FE, but I think we need to give the other extension owners a heads up about the issue, rather than just throwing them in the deep end and locking them out on a whim. There are obviously dependencies.

There are of course potential alternative ways to capture a FE rendering than trying to reconstruct a FE perspective in the BE. Using cURL comes to my mind, though you may need an authentication mechanism if you need to stop that content from becoming public (look for a BE cookie?).

Maybe this opens up a discussion of the historical immutability of TYPO3_MODE or the need for better FE simulation in the BE. But that discussion I guess should be pointed @TYPO3 core and not here.

..or maybe not (security?) and work arounds should be explored first, though ultimately it would be nice if extension  builders had either an official TYPO3 way of doing this or maybe an accessible BE API in realurl to encode speaking URLs on a as needed basis without the FE dependency.
i.e:

> RealUrlAPI::encode($fullyQualifiedUrl,$realUrlConf); 
> RealUrlAPI::decode($fullyQualifiedSpeakingUrl,$realUrlConf); 

Just my 2c.

**Comment by dmitryd** [comment]
> or maybe an accessible BE API in realurl to encode speaking URLs on a as needed basis without the FE dependency.

That was the initial plan but after the investigation it was not implemented because it is not feasible. Realurl may work properly only from inside the `typolink` function. Even if called directly in FE context, it still can produce inadequate results because it relies a lot on the functionality inside `typolink` and `linkData` functions. It also relies on certain TSFE functions and behavior that is altered by TS or parameters like `MP`. So doing it from BE would not be really possible.

Long time ago I had an extension called `pagepath`, which does exactly that: a BE API that invokes a special handler in FE mode that build a URL. That FE call was hidden and only BE API was exposed. But it did not really become popular. People wanted to call realurl directly and got all kind of funny issues sending me bug reports like 'realurl does not work with extension XYZ'. The only thing I could do is to reply like 'than ask the author of XYZ about it because realurl works fine in Frontend'.

So no official support for BE at all. Anybody, who does it from BE, does it on its own risk. This is NOT the right way to use realurl. And this WILL fail sooner or later.

**Comment by marvin-martian** [comment]
Then if you are at some point going to strictly enforce it, maybe a slow deprecation notice with a future target version for removal instead of just breaking dependent extensions without notice. Just to give a heads up. Some of these extensions like solr are running on quite a few large enterprise roll outs. 

I guess at some point routing paths will eventually will be in the core of Typo3. It makes sense to build it in. Many frameworks do this already out of the box.

**Comment by dmitryd** [comment]
> I guess at some point routing paths will eventually will be in the core of Typo3. It makes sense to build it in. Many frameworks do this already out of the box.

Yes and in that case realurl will be obsolete. There will be no need for hacks any more.
