### ISSUE TITLE
Cache expiration does not respect config.sys_language_uid

### ISSUE THREAD

**Issue by vertexvaar** [dmitryd/typo3-realurl#424]
A page is configured with the TypoScript setting `config.sys_language_uid = 3` (somewhere in the middle of a page tree).
When a speaking URL is generated for the page and the language uid "3" is stored within tx_realurl_pathdata (value retrieved from TSFE). After the page was renamed the hook will expire all entries with language_id = 0 (hardcoded), but not with the configured sys_language_uid.

**Comment by dmitryd** [comment]
The hook cannot access the configured value because it exists only in the Frontend but the hook is executed in the Backend. There is no language information associated with the page n the page level (in `pages` table). It exists in realurl tables but _currently_ I do not want to add another query because the case is rare and non-standard but any extra query will make realurl slower for everybody. I am not sure this particular case is worth slowing down everybody else.

You can always do it in a TYPO3 way by translating the page properly and hiding the default translation. Check the [corresponding document](https://docs.typo3.org/typo3cms/FrontendLocalizationGuide/LocalizationOverview/Index.html#hiding-default-translation-of-pages) to see how this should be done correctly.

**Comment by dmitryd** [comment]
I made extra checks and closing this because it is not fixable.
