### ISSUE TITLE
Error in conjunction with mount points

### ISSUE THREAD

**Issue by responseinformationsdesign** [dmitryd/typo3-realurl#433]
If master page (page withount mount point) is behind the page with mount point in the page tree a link to the master page jumps to the (first) page with mount point.

**Comment by dmitryd** [comment]
Please, post a picture of such page tree and show what pages do you mean. It is hard to understand this from the description.

**Comment by responseinformationsdesign** [comment]
**Case 1:**
```
root
- page 1
  + subpage 1.1
      ° subsubpage 1.1.1
- page 2
  + subpage 2.1 (mount point to subpage 1.1)
      ° subsubpage 2.1.1
```

Works as exspected as subpage 2.1 with mount point comes after 1.1 in page tree.


**Case 2:**
```
root
- page 1
  + subpage 1.1 (mount point to subpage 2.1)
      ° subsubpage 1.1.1
- page 2
  + subpage 2.1
      ° subsubpage 2.1.1
```

Error: Link for subpage 2.1 redirects to subpage 1.1

Therefore to avoid the redirect the "master page" always has to be first in page tree.

**Comment by dmitryd** [comment]
This is in menu, right? I just tested with menu in TYPO3 8 and I have similar effect **without realurl**. 

Here is my page tree:

<img width="142" alt="01-page-tree" src="https://cloud.githubusercontent.com/assets/306133/26520583/7b9d4916-42de-11e7-881a-7f3b3ba33321.png">

Now I go to a mount point page but however my mouse over `Subpage A` to see its URL:

<img width="164" alt="02-subpage-a-link" src="https://cloud.githubusercontent.com/assets/306133/26520588/989ce486-42de-11e7-87ab-bc38b86a9514.png">

The URL is with the mount point (should not be!)

However if I click on `Regular pages` and hower above the same menu item, I see totally different URL:

<img width="160" alt="03-subpage-a-link-without-mp" src="https://cloud.githubusercontent.com/assets/306133/26520595/b5bc83dc-42de-11e7-87fb-1e1f36bcf459.png">

It seems to me that menu code does something strange here. I have nothing special in my code, just some wraps with classes. But it is not working correctly without realurl too.

Could you check if your problem is reproducible without realurl?

**Comment by dmitryd** [comment]
No answer for a long time. Closing the issue.
