### ISSUE TITLE
special char breaks 404 page load

### ISSUE THREAD

**Issue by fresh-concept** [dmitryd/typo3-realurl#456]
realurl is manually implemented and working fine for the whole website.
a special 404-page is defined and perfectly loads on every url spelled in latin alphabet.

by using the "Г" / Ge (Cyrillic) in an url the standard "Oops, an error occurred!"-page appears instead of the defined 404-page.

"PHP Warning: Invalid argument supplied for foreach() in /www/[...]/typo3conf/ext/realurl/Classes/Decoder/UrlDecoder.php line 1318"

**Comment by dmitryd** [comment]
I cannot reproduce this. Tried many cyrillic letters in the URL (easy for me since I am russian ~hacker~). Make sure that your database encoding is correct (`utf8`). The problem will happen if your database encoding does not support such characters (for example, `latin1` does not). You can use `show create table pages` to see the encoding. Also `show full columns from pages` should show you that character set is `utf8_general_ci`. If you do not have access to mysql, try saving cyrillic letters in a page title in the Backend. If that does not work, your encoding is wrong.

**Comment by dmitryd** [comment]
No feedback provided -> closing.
