### ISSUE TITLE
TYPO3-Installtool -> TCA-Migration-Check -> RealUrl 2.2.1 -> TCA missing some definitions

### ISSUE THREAD

**Issue by Padina42** [dmitryd/typo3-realurl#479]
Version RealUrl 2.2.1 
Check TCA with TYPO3 8.7.1 Installtool -> TCA-Migration-Check

Messages

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_realurl_pathdata['columns']['expire']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_realurl_uniqalias['columns']['expire']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_realurl_urldata['columns']['expire']['config']

**Comment by MrGecco** [comment]
Can confirm that behaviour. TYPO3 v8.7.1

**Comment by dmitryd** [comment]
You can ignore it. These tables are not managed via TYPO3 Backend, therefore TCA for them neither needed, nor important.

**Comment by nico-herbig** [comment]
Hi Dmitry,

First of all, thank you very much for your great work. Even if the tables are not managed by the TYPO3 CMS Backend, it would still make sense to add the missing configuration options in order to avoid confusing TYPO3 integrators and to keep the bar in the TYPO3 install tool green.

Thanks
Nico

**Comment by dmitryd** [comment]
Please, make a pull request. It is very hard for me to find time these days for anything apart from my day time work.
