### ISSUE TITLE
UrlEncoder::encodeUrl() adds pages with `tx_realurl_exclude`-flag

### ISSUE THREAD

**Issue by smoebody** [dmitryd/typo3-realurl#496]
The method `UrlEncoder::encodeUrl()` adds pages which are marked as excluded from speaking urls.
After a request to typo3 this hook adds a new entry to the table `tx_realurl_pathdata`.

**Comment by dmitryd** [comment]
Answer: https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#excluding-pages-does-not-work

**Comment by useltmann** [comment]
Thats not the reason. My Page structure is like this
```
+  [0]root
|
+--+ [1]content (hidden in menu)
|  |
|  +--+ [2]locations (hidden in menu)
|  |  |
|  |  +--+ [3]springfield (hidden in menu)
|  |  |  |
|  |  |  +--+ [4]locations (hidden in menu)
|  |  |  |  |
|  +  +  +  +
|
+--+ [5]locations (pagetype: shortcut to page 2, excluded from realurl)
|  |
|  +--+ [6]springfield (pagetype: shortcut to page 3, excluded from realurl)
|  |  |
|  |  +--+ [7]locations (pagetype: shortcut to page 4, excluded from realurl)
|  |  |  |
+  +  +  +
```

The the intention is that path `/locations` shows me content-page 2. Instead realurl redirects me (307) to `/locations/springfield/locations` (and shows content-page 4). In the table `tx_realurl_pathdata` i could find an entry like this:
```
mysql> SELECT page_id, pagepath FROM typo3.tx_realurl_pathdata where pagepath='locations' AND expire=0;
+---------+-----------+
| page_id | pagepath  |
+---------------------+
|       2 | locations |
|       5 | locations |
|       7 | locations |
+---------+-----------+
4 rows in set (0.00 sec)
```
I only expect page 2 to be listed in this table.

**Comment by useltmann** [comment]
@dmitryd sorry for crossposting. im actually the issuer

**Comment by dmitryd** [comment]
Pages 5 and 7 directly violate [one of realurl restrictions](https://github.com/dmitryd/typo3-realurl/wiki/Notes-for-Integrators#page-titles): no pages with the same name on the same logical level. This page structure will not work correctly with realurl. This is documented in multiple places.

> I only expect page 2 to be listed in this table.

This expectation is incorrect. As I wrote above, last segment is not excluded from speaking urls, so it will exist in the table. So pages 5 and 7 will appear there but with wrong paths due to violated restriction.

Regarding the redirect, I cannot really tell what happens there.

In any case, I do not see any bugs here yet. Support discussions should happen in Slack. Next time, please, ask in Slack first. If you ask in the correct place, it helps me to optimize the work on realurl.
