### ISSUE TITLE
PHP Catchable Fatal Error with Bootstrap Package - realurl_autoconf.php not generated

### ISSUE THREAD

**Issue by thomasmstein** [dmitryd/typo3-realurl#53]
Updated to your latest release 2.0.3 and then 2.0.4 through the extension manager froman earlier version which came with latest bootstap_package (2.0.0 I believe). Initially worked and also realurl_autoconf.php was present.

I made a mistake and introduce typo3 domain records afterwards (and not before) which then produced errors (see below).
 
As to your instructions I tried to remove realurl_autoconf.php but found that the file was not present anymore and does not regenerate. 

Realurl seems to install correctly.

Thanks 

Thomas

ERROR:
PHP Catchable Fatal Error: Argument 2 passed to BK2K\BootstrapPackage\Hooks\RealUrl\AutoConfig::addConfigVersion2x() must be an instance of Tx\Realurl\Configuration\ConfigurationGenerator, instance of DmitryDulepov\Realurl\Configuration\AutomaticConfigurator given in /srv/www/sakia/cms/typo3conf/ext/bootstrap_package/Classes/Hooks/RealUrl/AutoConfig.php line 59

**Comment by dmitryd** [comment]
As you see the error is caused by `BK2K\BootstrapPackage\Hooks\RealUrl\AutoConfig::addConfigVersion2x()`. Please, contact the author of that extension. Realurl cannot be responsible for misbehavior of for 3<sup>rd</sup> party extensions. In general, don't use any 3<sup>rd</sup> party "configurators", "enhancers", etc. They cause more harm than good.

It also looks that you use some unofficial form of Realurl. Official Realurl never had a `Tx\Realurl\Configuration\ConfigurationGenerator,` class.

**Comment by dmitryd** [comment]
See https://github.com/benjaminkott/bootstrap_package/issues/317

**Comment by thomasmstein** [comment]
@dmitryd Thanks for reference and reply.
