### ISSUE TITLE
Error 404 when page has the same title as a sysfolder on the same level

### ISSUE THREAD

**Issue by tliegl** [dmitryd/typo3-realurl#56]
I think I have a similar problem like this: #42
Installation is with TYPO3 7.6.4 and realurl 2.0.4.

I have a page tree with three levels deep:

- top navigation
 - navpoint
   - subnavpoint

This leads to /top-navigation/navpoint/subnavpoint.html and the page is reachable.

Now I set the "top navigation" page to "Exclude from speaking URL". The page /navpoint.html is working after that change.

The url for the third level page results in /navpoint/subnavpoint.html, but when I click on the "subnavpoint" in the menu I get "Page not found. Reason: Segment "subnavpoint" was not a keyword for a postVarSet as expected on page with id=83."

**Comment by dmitryd** [comment]
#42 was about shortcuts but you don't mention shortcuts. Are you sure it is related?

I just tested with up to four levels (all of them are standard pages): works fine.

**Comment by tliegl** [comment]
Thanks for the feedback. Tried it with a new subtree and everything worked there. So I checked my pagetree again and found the real cause I think.

Additionally to the page "navpoint" under "top navigation" I have a folder also named "navpoint" in my pagetree. So the pagetree looks like this:

- top navigation
  - navpoint
    - subnavpoint
- navpoint (sysfolder)

When I rename the sysfolder to something else (although I want the sysfolder explicitely named like the normal page in this case) I get a "Page not found" error.

Can I do anything else than renaming the folder? Shouldn't sysfolders be excluded from the whole url generation process?

**Comment by dmitryd** [comment]
Folders are valid containers for pages, so they can also be in the URL, so they cannot be excluded.

Also consider realurl decoding flow. It sees `/navpoint/subnavpoint.html`. Firsts, it selectes `navpoint` for decoding. It started from the 1<sup>st</sup> level and looks through all pages there. It finds `navpoint` folder, which matches the segment. So it saves this page as a starting point for further lookup. Next, it takes `subnavpoint.html`. It strips `.html` and fetches all subpages of `navpoint` folder. It tries to find a page, whose title can be encoded as `subnavpoint`. Since it cannot find it, it assumes that `subnavpoint` must be a postVar (like `news` in `news/my-news-title`). It cannot find such postVar and it complains.

**Comment by dmitryd** [comment]
I should update docs that page titles must be unique on the same level. If we have the following structure, it ill not be possible to decode `news` segment or `news/backup` correctly because segment can be decoded to two different pages.

```
Root
|- News <-- standard page
|-- Single
|- News <-- folder
|-- Backup
```

**Comment by thomasmstein** [comment]
@dmitryd 
Just a thought - without deeper technical background - would a check for same titles and possible adding of a suffix solve the accidental 'breaking' by site maintainer be an option. Function could be switched on and off etc. and suffice for path addition selected. 
E.g.
```
Root
|- News <-- standard page
|-- Single
|- News_01 <-- folder Title with suffix "_01" if already on same level
|-- Backup

```
