### ISSUE TITLE
Typo3 v9.0 admin_get_tables issue

### ISSUE THREAD

**Issue by avionbg** [dmitryd/typo3-realurl#589]
I've tried github realurl version which by reading the dependency includes 9.0, but after installing the plugin I have error :
`Call to a member function admin_get_tables() on null`

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function admin_get_tables() on null | Error thrown in file /var/www/html/typo3conf/ext/realurl/class.ext_update.php in line 170. Requested URL: http://xxx.xxx.xxx.xxx/typo3/index.php?route=%%2Ftools%%2FExtensionmanagerExtensionmanager%%2F&token=121009d9960a0c135451d5fb47eacfdb7824eb90
  
 With typo3db_legacy (compatibility layer) it works ok for now, this should be in documentation..

**Comment by dmitryd** [comment]
Support for v9 does not exist. Dependency was updated only to try realurl with v9 using composer.

TYPO3 v9 is going to have its own speaking URL support. Currently there are no plans to make realurl work for v9.

Even if v9 drops speaking URL support, efforts to make realurl work with v9 will be huge because of many breaking changes in v9. I am not sure when and how I will have time for this.

For now, don;t use realurl with v9. It is incompatible.

**Comment by stefanrainer** [comment]
Hi Avionbg, I also tried to install realurl on Typo3 9 and now extension manage rdoes not work anymore. same error message as in your case (... on null) Can you give me some advice how to uninstall the extension and/or repair the extension manager?

thank you !!!

**Comment by dmitryd** [comment]
@stefanrainer 

* Remove it from web/typo3conf/ext/PackageStates.php
* Remove from disk
* Remove all files in web/typo3temp/cache or web/typo3temp/var/cache (whatever of them exists)

**Comment by stefanrainer** [comment]
Thank you very much :-)

------ Originalnachricht ------
Von: "Dmitry Dulepov" <notifications@github.com>
An: "dmitryd/typo3-realurl" <typo3-realurl@noreply.github.com>
Cc: "stefanrainer" <stefan@interzell.com>; "Mention" 
<mention@noreply.github.com>
Gesendet: 16.01.2019 11:10:57
Betreff: Re: [dmitryd/typo3-realurl] Typo3 v9.0 admin_get_tables issue 
(#589)
